// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atlas.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaylistRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaylistRequest) Reset()         { *m = PlaylistRequest{} }
func (m *PlaylistRequest) String() string { return proto.CompactTextString(m) }
func (*PlaylistRequest) ProtoMessage()    {}
func (*PlaylistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8ebe89c2f4b7977, []int{0}
}

func (m *PlaylistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistRequest.Unmarshal(m, b)
}
func (m *PlaylistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistRequest.Marshal(b, m, deterministic)
}
func (m *PlaylistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistRequest.Merge(m, src)
}
func (m *PlaylistRequest) XXX_Size() int {
	return xxx_messageInfo_PlaylistRequest.Size(m)
}
func (m *PlaylistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistRequest proto.InternalMessageInfo

type Playlist struct {
	Items                []*Playlist_PlaylistItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Playlist) Reset()         { *m = Playlist{} }
func (m *Playlist) String() string { return proto.CompactTextString(m) }
func (*Playlist) ProtoMessage()    {}
func (*Playlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8ebe89c2f4b7977, []int{1}
}

func (m *Playlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playlist.Unmarshal(m, b)
}
func (m *Playlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playlist.Marshal(b, m, deterministic)
}
func (m *Playlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playlist.Merge(m, src)
}
func (m *Playlist) XXX_Size() int {
	return xxx_messageInfo_Playlist.Size(m)
}
func (m *Playlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Playlist.DiscardUnknown(m)
}

var xxx_messageInfo_Playlist proto.InternalMessageInfo

func (m *Playlist) GetItems() []*Playlist_PlaylistItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type Playlist_PlaylistItem struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Playlist_PlaylistItem) Reset()         { *m = Playlist_PlaylistItem{} }
func (m *Playlist_PlaylistItem) String() string { return proto.CompactTextString(m) }
func (*Playlist_PlaylistItem) ProtoMessage()    {}
func (*Playlist_PlaylistItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8ebe89c2f4b7977, []int{1, 0}
}

func (m *Playlist_PlaylistItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playlist_PlaylistItem.Unmarshal(m, b)
}
func (m *Playlist_PlaylistItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playlist_PlaylistItem.Marshal(b, m, deterministic)
}
func (m *Playlist_PlaylistItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playlist_PlaylistItem.Merge(m, src)
}
func (m *Playlist_PlaylistItem) XXX_Size() int {
	return xxx_messageInfo_Playlist_PlaylistItem.Size(m)
}
func (m *Playlist_PlaylistItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Playlist_PlaylistItem.DiscardUnknown(m)
}

var xxx_messageInfo_Playlist_PlaylistItem proto.InternalMessageInfo

func (m *Playlist_PlaylistItem) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Playlist_PlaylistItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*PlaylistRequest)(nil), "message.PlaylistRequest")
	proto.RegisterType((*Playlist)(nil), "message.Playlist")
	proto.RegisterType((*Playlist_PlaylistItem)(nil), "message.Playlist.PlaylistItem")
}

func init() { proto.RegisterFile("atlas.proto", fileDescriptor_e8ebe89c2f4b7977) }

var fileDescriptor_e8ebe89c2f4b7977 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbf, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x51, 0x7f, 0xba, 0x72, 0xa1, 0x54, 0x93, 0xf1, 0x50, 0x8c, 0x27, 0x4f, 0x12, 0xb4,
	0x9d, 0x03, 0x49, 0xa6, 0x6c, 0xc1, 0x63, 0x36, 0xd9, 0x5c, 0x6c, 0x81, 0x64, 0x39, 0xbe, 0x73,
	0x20, 0x5b, 0xfe, 0xf4, 0x80, 0x62, 0x9b, 0x6c, 0xdf, 0x7d, 0xbc, 0x83, 0xf7, 0x78, 0xac, 0xc9,
	0x6a, 0x94, 0xfd, 0xe0, 0xc9, 0x8b, 0x77, 0x07, 0x88, 0xba, 0x81, 0xfc, 0x9b, 0x7f, 0xed, 0xad,
	0xbe, 0x58, 0x83, 0x54, 0xc2, 0x69, 0x04, 0xa4, 0xfc, 0xca, 0x78, 0x34, 0x3b, 0xf1, 0xcf, 0x5f,
	0x0d, 0x81, 0xc3, 0x84, 0x65, 0xcf, 0x45, 0xfc, 0xfb, 0x23, 0xa7, 0x47, 0x39, 0x27, 0x16, 0xd8,
	0x11, 0xb8, 0xf2, 0x1e, 0x4e, 0x57, 0xfc, 0xf3, 0x51, 0x8b, 0x94, 0x47, 0x47, 0x63, 0xa1, 0xd3,
	0x0e, 0x12, 0x96, 0xb1, 0xe2, 0xa3, 0x5c, 0x6e, 0x21, 0xf8, 0x4b, 0xaf, 0xa9, 0x4d, 0x9e, 0x82,
	0x0f, 0xbc, 0xd9, 0x1e, 0xd6, 0x8d, 0xa1, 0x76, 0xac, 0x64, 0xed, 0x9d, 0x6a, 0x06, 0x80, 0xce,
	0xf9, 0xba, 0x35, 0x6a, 0xb4, 0x64, 0x9c, 0x26, 0x50, 0x08, 0xc3, 0xd9, 0xd4, 0x80, 0x2a, 0xac,
	0x52, 0x61, 0xd5, 0xc4, 0x53, 0xc3, 0xea, 0x2d, 0xc8, 0xbf, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0x2d, 0x1f, 0x40, 0xf9, 0x00, 0x00, 0x00,
}
