// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myanimelist.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type SearchReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReply) Reset()         { *m = SearchReply{} }
func (m *SearchReply) String() string { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()    {}
func (*SearchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{2}
}

func (m *SearchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReply.Unmarshal(m, b)
}
func (m *SearchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReply.Marshal(b, m, deterministic)
}
func (m *SearchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReply.Merge(m, src)
}
func (m *SearchReply) XXX_Size() int {
	return xxx_messageInfo_SearchReply.Size(m)
}
func (m *SearchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReply proto.InternalMessageInfo

type CurrentResultsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentResultsRequest) Reset()         { *m = CurrentResultsRequest{} }
func (m *CurrentResultsRequest) String() string { return proto.CompactTextString(m) }
func (*CurrentResultsRequest) ProtoMessage()    {}
func (*CurrentResultsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{3}
}

func (m *CurrentResultsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentResultsRequest.Unmarshal(m, b)
}
func (m *CurrentResultsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentResultsRequest.Marshal(b, m, deterministic)
}
func (m *CurrentResultsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentResultsRequest.Merge(m, src)
}
func (m *CurrentResultsRequest) XXX_Size() int {
	return xxx_messageInfo_CurrentResultsRequest.Size(m)
}
func (m *CurrentResultsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentResultsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentResultsRequest proto.InternalMessageInfo

type CurrentResultsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentResultsReply) Reset()         { *m = CurrentResultsReply{} }
func (m *CurrentResultsReply) String() string { return proto.CompactTextString(m) }
func (*CurrentResultsReply) ProtoMessage()    {}
func (*CurrentResultsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{4}
}

func (m *CurrentResultsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentResultsReply.Unmarshal(m, b)
}
func (m *CurrentResultsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentResultsReply.Marshal(b, m, deterministic)
}
func (m *CurrentResultsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentResultsReply.Merge(m, src)
}
func (m *CurrentResultsReply) XXX_Size() int {
	return xxx_messageInfo_CurrentResultsReply.Size(m)
}
func (m *CurrentResultsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentResultsReply.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentResultsReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SearchRequest)(nil), "message.SearchRequest")
	proto.RegisterType((*Result)(nil), "message.Result")
	proto.RegisterType((*SearchReply)(nil), "message.SearchReply")
	proto.RegisterType((*CurrentResultsRequest)(nil), "message.CurrentResultsRequest")
	proto.RegisterType((*CurrentResultsReply)(nil), "message.CurrentResultsReply")
}

func init() { proto.RegisterFile("myanimelist.proto", fileDescriptor_7365bf8e2ee52b0c) }

var fileDescriptor_7365bf8e2ee52b0c = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xce, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0xc5, 0xf1, 0xad, 0xdf, 0x47, 0xa4, 0x88, 0x4a, 0x71, 0xcf, 0x03, 0x34, 0x83, 0x6f, 0xa0,
	0xb3, 0x08, 0x75, 0x73, 0x4b, 0xc3, 0xa1, 0x0d, 0x24, 0x4d, 0xbd, 0xf7, 0x46, 0xe8, 0xdb, 0x0b,
	0xd5, 0x82, 0xba, 0x9e, 0x1f, 0x07, 0xfe, 0x6a, 0x13, 0x27, 0x3b, 0xf8, 0x88, 0xe0, 0x59, 0xea,
	0x91, 0x92, 0xa4, 0xed, 0x5f, 0x04, 0xb3, 0xed, 0xa0, 0xd7, 0xaa, 0xbc, 0xc2, 0x92, 0xeb, 0x1b,
	0xdc, 0x33, 0x58, 0xf4, 0xbf, 0x2a, 0x1a, 0x70, 0x0e, 0xa2, 0x4b, 0xb5, 0x5a, 0x68, 0x0c, 0x93,
	0xde, 0xab, 0xea, 0x94, 0x89, 0x30, 0xc8, 0xcb, 0x79, 0x79, 0x54, 0x6a, 0xf7, 0x0b, 0x63, 0x98,
	0x8e, 0x97, 0xdb, 0xb9, 0xf3, 0xd2, 0xe7, 0xb6, 0x76, 0x29, 0x9a, 0x8e, 0x80, 0x21, 0x26, 0xd7,
	0x7b, 0x93, 0x83, 0xf8, 0x68, 0x05, 0x86, 0x41, 0x0f, 0xef, 0xc0, 0xe6, 0xa3, 0xcf, 0xcc, 0x7d,
	0x5f, 0xcb, 0x3b, 0xb5, 0x2d, 0x66, 0x3a, 0x3c, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xd6, 0x29,
	0x64, 0xcf, 0x00, 0x00, 0x00,
}
