# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torrent/service/torrent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='torrent/service/torrent.proto',
  package='torrent',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dtorrent/service/torrent.proto\x12\x07torrent\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fShutdownRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rShutdownReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x13\x41\x64\x64MagnetUriRequest\x12\x0e\n\x06magnet\x18\x01 \x01(\t\"!\n\x11\x41\x64\x64MagnetUriReply\x12\x0c\n\x04hash\x18\x01 \x01(\t\"$\n\x14RemoveTorrentRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x14\n\x12RemoveTorrentReply\"#\n\x13PauseTorrentRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x13\n\x11PauseTorrentReply\"$\n\x14ResumeTorrentRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x14\n\x12ResumeTorrentReply\"\xaa\x01\n\rTorrentStatus\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x15\n\rdownload_rate\x18\x04 \x01(\x11\x12\x13\n\x0bupload_rate\x18\x05 \x01(\x11\x12\r\n\x05peers\x18\x06 \x01(\x11\x12\r\n\x05seeds\x18\x07 \x01(\x11\x12\r\n\x05state\x18\x08 \x01(\t\x12\x12\n\ntotal_size\x18\t \x01(\x04\"\x19\n\x17\x41llTorrentStatusRequest\"K\n\x15\x41llTorrentStatusReply\x12\x32\n\x12\x61ll_torrent_status\x18\x01 \x03(\x0b\x32\x16.torrent.TorrentStatus2\xff\x03\n\x07Torrent\x12\x30\n\x04Ping\x12\x14.torrent.PingRequest\x1a\x12.torrent.PingReply\x12<\n\x08Shutdown\x12\x18.torrent.ShutdownRequest\x1a\x16.torrent.ShutdownReply\x12H\n\x0c\x41\x64\x64MagnetUri\x12\x1c.torrent.AddMagnetUriRequest\x1a\x1a.torrent.AddMagnetUriReply\x12K\n\rRemoveTorrent\x12\x1d.torrent.RemoveTorrentRequest\x1a\x1b.torrent.RemoveTorrentReply\x12H\n\x0cPauseTorrent\x12\x1c.torrent.PauseTorrentRequest\x1a\x1a.torrent.PauseTorrentReply\x12K\n\rResumeTorrent\x12\x1d.torrent.ResumeTorrentRequest\x1a\x1b.torrent.ResumeTorrentReply\x12V\n\x10\x41llTorrentStatus\x12 .torrent.AllTorrentStatusRequest\x1a\x1e.torrent.AllTorrentStatusReply0\x01\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='torrent.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='torrent.PingRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=72,
)


_PINGREPLY = _descriptor.Descriptor(
  name='PingReply',
  full_name='torrent.PingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='torrent.PingReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=102,
)


_SHUTDOWNREQUEST = _descriptor.Descriptor(
  name='ShutdownRequest',
  full_name='torrent.ShutdownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='torrent.ShutdownRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=138,
)


_SHUTDOWNREPLY = _descriptor.Descriptor(
  name='ShutdownReply',
  full_name='torrent.ShutdownReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='torrent.ShutdownReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=172,
)


_ADDMAGNETURIREQUEST = _descriptor.Descriptor(
  name='AddMagnetUriRequest',
  full_name='torrent.AddMagnetUriRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magnet', full_name='torrent.AddMagnetUriRequest.magnet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=211,
)


_ADDMAGNETURIREPLY = _descriptor.Descriptor(
  name='AddMagnetUriReply',
  full_name='torrent.AddMagnetUriReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='torrent.AddMagnetUriReply.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=246,
)


_REMOVETORRENTREQUEST = _descriptor.Descriptor(
  name='RemoveTorrentRequest',
  full_name='torrent.RemoveTorrentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='torrent.RemoveTorrentRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=284,
)


_REMOVETORRENTREPLY = _descriptor.Descriptor(
  name='RemoveTorrentReply',
  full_name='torrent.RemoveTorrentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=306,
)


_PAUSETORRENTREQUEST = _descriptor.Descriptor(
  name='PauseTorrentRequest',
  full_name='torrent.PauseTorrentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='torrent.PauseTorrentRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=343,
)


_PAUSETORRENTREPLY = _descriptor.Descriptor(
  name='PauseTorrentReply',
  full_name='torrent.PauseTorrentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=364,
)


_RESUMETORRENTREQUEST = _descriptor.Descriptor(
  name='ResumeTorrentRequest',
  full_name='torrent.ResumeTorrentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='torrent.ResumeTorrentRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=402,
)


_RESUMETORRENTREPLY = _descriptor.Descriptor(
  name='ResumeTorrentReply',
  full_name='torrent.ResumeTorrentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=424,
)


_TORRENTSTATUS = _descriptor.Descriptor(
  name='TorrentStatus',
  full_name='torrent.TorrentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='torrent.TorrentStatus.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='torrent.TorrentStatus.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='torrent.TorrentStatus.progress', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_rate', full_name='torrent.TorrentStatus.download_rate', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload_rate', full_name='torrent.TorrentStatus.upload_rate', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peers', full_name='torrent.TorrentStatus.peers', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seeds', full_name='torrent.TorrentStatus.seeds', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='torrent.TorrentStatus.state', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_size', full_name='torrent.TorrentStatus.total_size', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=597,
)


_ALLTORRENTSTATUSREQUEST = _descriptor.Descriptor(
  name='AllTorrentStatusRequest',
  full_name='torrent.AllTorrentStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=624,
)


_ALLTORRENTSTATUSREPLY = _descriptor.Descriptor(
  name='AllTorrentStatusReply',
  full_name='torrent.AllTorrentStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='all_torrent_status', full_name='torrent.AllTorrentStatusReply.all_torrent_status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=701,
)

_ALLTORRENTSTATUSREPLY.fields_by_name['all_torrent_status'].message_type = _TORRENTSTATUS
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingReply'] = _PINGREPLY
DESCRIPTOR.message_types_by_name['ShutdownRequest'] = _SHUTDOWNREQUEST
DESCRIPTOR.message_types_by_name['ShutdownReply'] = _SHUTDOWNREPLY
DESCRIPTOR.message_types_by_name['AddMagnetUriRequest'] = _ADDMAGNETURIREQUEST
DESCRIPTOR.message_types_by_name['AddMagnetUriReply'] = _ADDMAGNETURIREPLY
DESCRIPTOR.message_types_by_name['RemoveTorrentRequest'] = _REMOVETORRENTREQUEST
DESCRIPTOR.message_types_by_name['RemoveTorrentReply'] = _REMOVETORRENTREPLY
DESCRIPTOR.message_types_by_name['PauseTorrentRequest'] = _PAUSETORRENTREQUEST
DESCRIPTOR.message_types_by_name['PauseTorrentReply'] = _PAUSETORRENTREPLY
DESCRIPTOR.message_types_by_name['ResumeTorrentRequest'] = _RESUMETORRENTREQUEST
DESCRIPTOR.message_types_by_name['ResumeTorrentReply'] = _RESUMETORRENTREPLY
DESCRIPTOR.message_types_by_name['TorrentStatus'] = _TORRENTSTATUS
DESCRIPTOR.message_types_by_name['AllTorrentStatusRequest'] = _ALLTORRENTSTATUSREQUEST
DESCRIPTOR.message_types_by_name['AllTorrentStatusReply'] = _ALLTORRENTSTATUSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), {
  'DESCRIPTOR' : _PINGREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.PingReply)
  })
_sym_db.RegisterMessage(PingReply)

ShutdownRequest = _reflection.GeneratedProtocolMessageType('ShutdownRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.ShutdownRequest)
  })
_sym_db.RegisterMessage(ShutdownRequest)

ShutdownReply = _reflection.GeneratedProtocolMessageType('ShutdownReply', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.ShutdownReply)
  })
_sym_db.RegisterMessage(ShutdownReply)

AddMagnetUriRequest = _reflection.GeneratedProtocolMessageType('AddMagnetUriRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMAGNETURIREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.AddMagnetUriRequest)
  })
_sym_db.RegisterMessage(AddMagnetUriRequest)

AddMagnetUriReply = _reflection.GeneratedProtocolMessageType('AddMagnetUriReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDMAGNETURIREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.AddMagnetUriReply)
  })
_sym_db.RegisterMessage(AddMagnetUriReply)

RemoveTorrentRequest = _reflection.GeneratedProtocolMessageType('RemoveTorrentRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVETORRENTREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.RemoveTorrentRequest)
  })
_sym_db.RegisterMessage(RemoveTorrentRequest)

RemoveTorrentReply = _reflection.GeneratedProtocolMessageType('RemoveTorrentReply', (_message.Message,), {
  'DESCRIPTOR' : _REMOVETORRENTREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.RemoveTorrentReply)
  })
_sym_db.RegisterMessage(RemoveTorrentReply)

PauseTorrentRequest = _reflection.GeneratedProtocolMessageType('PauseTorrentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAUSETORRENTREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.PauseTorrentRequest)
  })
_sym_db.RegisterMessage(PauseTorrentRequest)

PauseTorrentReply = _reflection.GeneratedProtocolMessageType('PauseTorrentReply', (_message.Message,), {
  'DESCRIPTOR' : _PAUSETORRENTREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.PauseTorrentReply)
  })
_sym_db.RegisterMessage(PauseTorrentReply)

ResumeTorrentRequest = _reflection.GeneratedProtocolMessageType('ResumeTorrentRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESUMETORRENTREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.ResumeTorrentRequest)
  })
_sym_db.RegisterMessage(ResumeTorrentRequest)

ResumeTorrentReply = _reflection.GeneratedProtocolMessageType('ResumeTorrentReply', (_message.Message,), {
  'DESCRIPTOR' : _RESUMETORRENTREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.ResumeTorrentReply)
  })
_sym_db.RegisterMessage(ResumeTorrentReply)

TorrentStatus = _reflection.GeneratedProtocolMessageType('TorrentStatus', (_message.Message,), {
  'DESCRIPTOR' : _TORRENTSTATUS,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.TorrentStatus)
  })
_sym_db.RegisterMessage(TorrentStatus)

AllTorrentStatusRequest = _reflection.GeneratedProtocolMessageType('AllTorrentStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLTORRENTSTATUSREQUEST,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.AllTorrentStatusRequest)
  })
_sym_db.RegisterMessage(AllTorrentStatusRequest)

AllTorrentStatusReply = _reflection.GeneratedProtocolMessageType('AllTorrentStatusReply', (_message.Message,), {
  'DESCRIPTOR' : _ALLTORRENTSTATUSREPLY,
  '__module__' : 'torrent.service.torrent_pb2'
  # @@protoc_insertion_point(class_scope:torrent.AllTorrentStatusReply)
  })
_sym_db.RegisterMessage(AllTorrentStatusReply)



_TORRENT = _descriptor.ServiceDescriptor(
  name='Torrent',
  full_name='torrent.Torrent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=704,
  serialized_end=1215,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='torrent.Torrent.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='torrent.Torrent.Shutdown',
    index=1,
    containing_service=None,
    input_type=_SHUTDOWNREQUEST,
    output_type=_SHUTDOWNREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddMagnetUri',
    full_name='torrent.Torrent.AddMagnetUri',
    index=2,
    containing_service=None,
    input_type=_ADDMAGNETURIREQUEST,
    output_type=_ADDMAGNETURIREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveTorrent',
    full_name='torrent.Torrent.RemoveTorrent',
    index=3,
    containing_service=None,
    input_type=_REMOVETORRENTREQUEST,
    output_type=_REMOVETORRENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PauseTorrent',
    full_name='torrent.Torrent.PauseTorrent',
    index=4,
    containing_service=None,
    input_type=_PAUSETORRENTREQUEST,
    output_type=_PAUSETORRENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResumeTorrent',
    full_name='torrent.Torrent.ResumeTorrent',
    index=5,
    containing_service=None,
    input_type=_RESUMETORRENTREQUEST,
    output_type=_RESUMETORRENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AllTorrentStatus',
    full_name='torrent.Torrent.AllTorrentStatus',
    index=6,
    containing_service=None,
    input_type=_ALLTORRENTSTATUSREQUEST,
    output_type=_ALLTORRENTSTATUSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TORRENT)

DESCRIPTOR.services_by_name['Torrent'] = _TORRENT

# @@protoc_insertion_point(module_scope)
