// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: ultimate_torrent.proto

/*
Package ultimate_torrent is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package ultimate_torrent

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_UltimateTorrent_Ping_0(ctx context.Context, marshaler runtime.Marshaler, client UltimateTorrentClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq PingRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.Ping(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func request_UltimateTorrent_AllTorrentStatus_0(ctx context.Context, marshaler runtime.Marshaler, client UltimateTorrentClient, req *http.Request, pathParams map[string]string) (UltimateTorrent_AllTorrentStatusClient, runtime.ServerMetadata, error) {
	var protoReq AllTorrentStatusRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.AllTorrentStatus(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterUltimateTorrentHandlerFromEndpoint is same as RegisterUltimateTorrentHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterUltimateTorrentHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterUltimateTorrentHandler(ctx, mux, conn)
}

// RegisterUltimateTorrentHandler registers the http handlers for service UltimateTorrent to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterUltimateTorrentHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterUltimateTorrentHandlerClient(ctx, mux, NewUltimateTorrentClient(conn))
}

// RegisterUltimateTorrentHandlerClient registers the http handlers for service UltimateTorrent
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "UltimateTorrentClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "UltimateTorrentClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "UltimateTorrentClient" to call the correct interceptors.
func RegisterUltimateTorrentHandlerClient(ctx context.Context, mux *runtime.ServeMux, client UltimateTorrentClient) error {

	mux.Handle("POST", pattern_UltimateTorrent_Ping_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_UltimateTorrent_Ping_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_UltimateTorrent_Ping_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_UltimateTorrent_AllTorrentStatus_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_UltimateTorrent_AllTorrentStatus_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_UltimateTorrent_AllTorrentStatus_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_UltimateTorrent_Ping_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"ultimate-torrent", "ping"}, ""))

	pattern_UltimateTorrent_AllTorrentStatus_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"ultimate-torrent", "all-torrent-status"}, ""))
)

var (
	forward_UltimateTorrent_Ping_0 = runtime.ForwardResponseMessage

	forward_UltimateTorrent_AllTorrentStatus_0 = runtime.ForwardResponseStream
)
