// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myanimelist.proto

package myanimelist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	message "github.com/greenmochi/ultimate/services/myanimelist/proto/myanimelist/message"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The ping message containing the user's name.
type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the greetings
type PingReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{2}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownReply) Reset()         { *m = ShutdownReply{} }
func (m *ShutdownReply) String() string { return proto.CompactTextString(m) }
func (*ShutdownReply) ProtoMessage()    {}
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{3}
}

func (m *ShutdownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownReply.Unmarshal(m, b)
}
func (m *ShutdownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownReply.Marshal(b, m, deterministic)
}
func (m *ShutdownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownReply.Merge(m, src)
}
func (m *ShutdownReply) XXX_Size() int {
	return xxx_messageInfo_ShutdownReply.Size(m)
}
func (m *ShutdownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingRequest)(nil), "myanimelist.PingRequest")
	proto.RegisterType((*PingReply)(nil), "myanimelist.PingReply")
	proto.RegisterType((*ShutdownRequest)(nil), "myanimelist.ShutdownRequest")
	proto.RegisterType((*ShutdownReply)(nil), "myanimelist.ShutdownReply")
}

func init() { proto.RegisterFile("myanimelist.proto", fileDescriptor_7365bf8e2ee52b0c) }

var fileDescriptor_7365bf8e2ee52b0c = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xad, 0x4c, 0xcc,
	0xcb, 0xcc, 0x4d, 0xcd, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x92, 0x92, 0xcc, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xc7, 0x50, 0xa7, 0xa4, 0xce,
	0xc5, 0x1d, 0x90, 0x99, 0x97, 0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc1, 0xc5,
	0x0e, 0x55, 0x2b, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x2a, 0xa9, 0x72, 0x71, 0x42,
	0x14, 0x16, 0xe4, 0x54, 0xe2, 0x51, 0x26, 0xc8, 0xc5, 0x1f, 0x9c, 0x51, 0x5a, 0x92, 0x92, 0x5f,
	0x9e, 0x07, 0x35, 0x53, 0x89, 0x9f, 0x8b, 0x17, 0x21, 0x54, 0x90, 0x53, 0x69, 0x34, 0x95, 0x89,
	0x8b, 0xdb, 0xb7, 0xd2, 0x11, 0xe4, 0x12, 0x9f, 0xcc, 0xe2, 0x12, 0x21, 0x0b, 0x2e, 0x16, 0x90,
	0xd1, 0x42, 0x12, 0x7a, 0xc8, 0xee, 0x43, 0x72, 0x96, 0x94, 0x18, 0x16, 0x19, 0x90, 0x3b, 0x5c,
	0xb8, 0x38, 0x60, 0x46, 0x0b, 0xc9, 0xa0, 0xa8, 0x41, 0x73, 0x84, 0x94, 0x14, 0x0e, 0x59, 0x90,
	0x29, 0x66, 0x5c, 0x6c, 0xc1, 0xa9, 0x89, 0x45, 0xc9, 0x19, 0x42, 0x62, 0x7a, 0x50, 0x7f, 0xe8,
	0x41, 0x04, 0x60, 0xba, 0x45, 0x30, 0xc4, 0x41, 0xfa, 0xfc, 0xb8, 0xf8, 0x9c, 0x4b, 0x8b, 0x8a,
	0x52, 0xf3, 0x4a, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x8a, 0x85, 0xe4, 0xe0, 0xea, 0x50, 0x25,
	0x60, 0xe6, 0xc8, 0xe0, 0x94, 0x2f, 0xc8, 0xa9, 0x4c, 0x62, 0x03, 0x47, 0x89, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x57, 0x6e, 0x31, 0xcf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyAnimeListClient is the client API for MyAnimeList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyAnimeListClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	Search(ctx context.Context, in *message.SearchRequest, opts ...grpc.CallOption) (*message.SearchReply, error)
	CurrentResults(ctx context.Context, in *message.CurrentResultsRequest, opts ...grpc.CallOption) (*message.CurrentResultsReply, error)
}

type myAnimeListClient struct {
	cc *grpc.ClientConn
}

func NewMyAnimeListClient(cc *grpc.ClientConn) MyAnimeListClient {
	return &myAnimeListClient{cc}
}

func (c *myAnimeListClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myAnimeListClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myAnimeListClient) Search(ctx context.Context, in *message.SearchRequest, opts ...grpc.CallOption) (*message.SearchReply, error) {
	out := new(message.SearchReply)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myAnimeListClient) CurrentResults(ctx context.Context, in *message.CurrentResultsRequest, opts ...grpc.CallOption) (*message.CurrentResultsReply, error) {
	out := new(message.CurrentResultsReply)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/CurrentResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyAnimeListServer is the server API for MyAnimeList service.
type MyAnimeListServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	Search(context.Context, *message.SearchRequest) (*message.SearchReply, error)
	CurrentResults(context.Context, *message.CurrentResultsRequest) (*message.CurrentResultsReply, error)
}

// UnimplementedMyAnimeListServer can be embedded to have forward compatible implementations.
type UnimplementedMyAnimeListServer struct {
}

func (*UnimplementedMyAnimeListServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMyAnimeListServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (*UnimplementedMyAnimeListServer) Search(ctx context.Context, req *message.SearchRequest) (*message.SearchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedMyAnimeListServer) CurrentResults(ctx context.Context, req *message.CurrentResultsRequest) (*message.CurrentResultsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentResults not implemented")
}

func RegisterMyAnimeListServer(s *grpc.Server, srv MyAnimeListServer) {
	s.RegisterService(&_MyAnimeList_serviceDesc, srv)
}

func _MyAnimeList_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyAnimeList_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyAnimeList_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).Search(ctx, req.(*message.SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyAnimeList_CurrentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.CurrentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).CurrentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/CurrentResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).CurrentResults(ctx, req.(*message.CurrentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyAnimeList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myanimelist.MyAnimeList",
	HandlerType: (*MyAnimeListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MyAnimeList_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _MyAnimeList_Shutdown_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MyAnimeList_Search_Handler,
		},
		{
			MethodName: "CurrentResults",
			Handler:    _MyAnimeList_CurrentResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myanimelist.proto",
}
