# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ultimate_torrent.service import ultimate_torrent_pb2 as ultimate__torrent_dot_service_dot_ultimate__torrent__pb2


class UltimateTorrentStub(object):
  """The ultimate-torrent's service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/Ping',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PingRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PingReply.FromString,
        )
    self.Shutdown = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/Shutdown',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ShutdownRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ShutdownReply.FromString,
        )
    self.AddMagnetUri = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/AddMagnetUri',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AddMagnetUriRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AddMagnetUriReply.FromString,
        )
    self.RemoveTorrent = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/RemoveTorrent',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.RemoveTorrentRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.RemoveTorrentReply.FromString,
        )
    self.PauseTorrent = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/PauseTorrent',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PauseTorrentRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PauseTorrentReply.FromString,
        )
    self.ResumeTorrent = channel.unary_unary(
        '/ultimate_torrent.UltimateTorrent/ResumeTorrent',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ResumeTorrentRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ResumeTorrentReply.FromString,
        )
    self.AllTorrentStatus = channel.unary_stream(
        '/ultimate_torrent.UltimateTorrent/AllTorrentStatus',
        request_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AllTorrentStatusRequest.SerializeToString,
        response_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AllTorrentStatusReply.FromString,
        )


class UltimateTorrentServicer(object):
  """The ultimate-torrent's service definition.
  """

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Shutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMagnetUri(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveTorrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PauseTorrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResumeTorrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AllTorrentStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UltimateTorrentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PingRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PingReply.SerializeToString,
      ),
      'Shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.Shutdown,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ShutdownRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ShutdownReply.SerializeToString,
      ),
      'AddMagnetUri': grpc.unary_unary_rpc_method_handler(
          servicer.AddMagnetUri,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AddMagnetUriRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AddMagnetUriReply.SerializeToString,
      ),
      'RemoveTorrent': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveTorrent,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.RemoveTorrentRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.RemoveTorrentReply.SerializeToString,
      ),
      'PauseTorrent': grpc.unary_unary_rpc_method_handler(
          servicer.PauseTorrent,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PauseTorrentRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.PauseTorrentReply.SerializeToString,
      ),
      'ResumeTorrent': grpc.unary_unary_rpc_method_handler(
          servicer.ResumeTorrent,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ResumeTorrentRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.ResumeTorrentReply.SerializeToString,
      ),
      'AllTorrentStatus': grpc.unary_stream_rpc_method_handler(
          servicer.AllTorrentStatus,
          request_deserializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AllTorrentStatusRequest.FromString,
          response_serializer=ultimate__torrent_dot_service_dot_ultimate__torrent__pb2.AllTorrentStatusReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ultimate_torrent.UltimateTorrent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
