// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myanimelist.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Username struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{0}
}

func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (m *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(m, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserAnimeList struct {
	Username             string                     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserAnime            []*UserAnimeList_UserAnime `protobuf:"bytes,2,rep,name=user_anime,json=userAnime,proto3" json:"user_anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UserAnimeList) Reset()         { *m = UserAnimeList{} }
func (m *UserAnimeList) String() string { return proto.CompactTextString(m) }
func (*UserAnimeList) ProtoMessage()    {}
func (*UserAnimeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1}
}

func (m *UserAnimeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAnimeList.Unmarshal(m, b)
}
func (m *UserAnimeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAnimeList.Marshal(b, m, deterministic)
}
func (m *UserAnimeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAnimeList.Merge(m, src)
}
func (m *UserAnimeList) XXX_Size() int {
	return xxx_messageInfo_UserAnimeList.Size(m)
}
func (m *UserAnimeList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAnimeList.DiscardUnknown(m)
}

var xxx_messageInfo_UserAnimeList proto.InternalMessageInfo

func (m *UserAnimeList) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserAnimeList) GetUserAnime() []*UserAnimeList_UserAnime {
	if m != nil {
		return m.UserAnime
	}
	return nil
}

type UserAnimeList_UserAnime struct {
	Status                int32                                `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Score                 int32                                `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Tags                  string                               `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	IsRewatching          string                               `protobuf:"bytes,4,opt,name=is_rewatching,json=isRewatching,proto3" json:"is_rewatching,omitempty"`
	NumWatchedEpisodes    int32                                `protobuf:"varint,5,opt,name=num_watched_episodes,json=numWatchedEpisodes,proto3" json:"num_watched_episodes,omitempty"`
	AnimeTitle            string                               `protobuf:"bytes,6,opt,name=anime_title,json=animeTitle,proto3" json:"anime_title,omitempty"`
	AnimeNumEpisodes      int32                                `protobuf:"varint,7,opt,name=anime_num_episodes,json=animeNumEpisodes,proto3" json:"anime_num_episodes,omitempty"`
	AnimeAiringStatus     int32                                `protobuf:"varint,8,opt,name=anime_airing_status,json=animeAiringStatus,proto3" json:"anime_airing_status,omitempty"`
	AnimeId               int32                                `protobuf:"varint,9,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	AnimeStudios          string                               `protobuf:"bytes,10,opt,name=anime_studios,json=animeStudios,proto3" json:"anime_studios,omitempty"`
	AnimeLicensors        string                               `protobuf:"bytes,11,opt,name=anime_licensors,json=animeLicensors,proto3" json:"anime_licensors,omitempty"`
	AnimeSeason           *UserAnimeList_UserAnime_AnimeSeason `protobuf:"bytes,12,opt,name=anime_season,json=animeSeason,proto3" json:"anime_season,omitempty"`
	HasEpisodeVideo       bool                                 `protobuf:"varint,13,opt,name=has_episode_video,json=hasEpisodeVideo,proto3" json:"has_episode_video,omitempty"`
	HasPromotionVideo     bool                                 `protobuf:"varint,14,opt,name=has_promotion_video,json=hasPromotionVideo,proto3" json:"has_promotion_video,omitempty"`
	HasVideo              bool                                 `protobuf:"varint,15,opt,name=has_video,json=hasVideo,proto3" json:"has_video,omitempty"`
	VideoUrl              string                               `protobuf:"bytes,16,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	AnimeUrl              string                               `protobuf:"bytes,17,opt,name=anime_url,json=animeUrl,proto3" json:"anime_url,omitempty"`
	AnimeImagePath        string                               `protobuf:"bytes,18,opt,name=anime_image_path,json=animeImagePath,proto3" json:"anime_image_path,omitempty"`
	IsAddedToList         bool                                 `protobuf:"varint,19,opt,name=is_added_to_list,json=isAddedToList,proto3" json:"is_added_to_list,omitempty"`
	AnimeMediaTypeString  string                               `protobuf:"bytes,20,opt,name=anime_media_type_string,json=animeMediaTypeString,proto3" json:"anime_media_type_string,omitempty"`
	AnimeMpaaRatingString string                               `protobuf:"bytes,21,opt,name=anime_mpaa_rating_string,json=animeMpaaRatingString,proto3" json:"anime_mpaa_rating_string,omitempty"`
	StartDateString       string                               `protobuf:"bytes,22,opt,name=start_date_string,json=startDateString,proto3" json:"start_date_string,omitempty"`
	FinishDateString      string                               `protobuf:"bytes,23,opt,name=finish_date_string,json=finishDateString,proto3" json:"finish_date_string,omitempty"`
	AnimeStartDateString  string                               `protobuf:"bytes,24,opt,name=anime_start_date_string,json=animeStartDateString,proto3" json:"anime_start_date_string,omitempty"`
	AnimeEndDateString    string                               `protobuf:"bytes,25,opt,name=anime_end_date_string,json=animeEndDateString,proto3" json:"anime_end_date_string,omitempty"`
	DaysString            int32                                `protobuf:"varint,26,opt,name=days_string,json=daysString,proto3" json:"days_string,omitempty"`
	StorageString         string                               `protobuf:"bytes,27,opt,name=storage_string,json=storageString,proto3" json:"storage_string,omitempty"`
	PriorityString        string                               `protobuf:"bytes,28,opt,name=priority_string,json=priorityString,proto3" json:"priority_string,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *UserAnimeList_UserAnime) Reset()         { *m = UserAnimeList_UserAnime{} }
func (m *UserAnimeList_UserAnime) String() string { return proto.CompactTextString(m) }
func (*UserAnimeList_UserAnime) ProtoMessage()    {}
func (*UserAnimeList_UserAnime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1, 0}
}

func (m *UserAnimeList_UserAnime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAnimeList_UserAnime.Unmarshal(m, b)
}
func (m *UserAnimeList_UserAnime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAnimeList_UserAnime.Marshal(b, m, deterministic)
}
func (m *UserAnimeList_UserAnime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAnimeList_UserAnime.Merge(m, src)
}
func (m *UserAnimeList_UserAnime) XXX_Size() int {
	return xxx_messageInfo_UserAnimeList_UserAnime.Size(m)
}
func (m *UserAnimeList_UserAnime) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAnimeList_UserAnime.DiscardUnknown(m)
}

var xxx_messageInfo_UserAnimeList_UserAnime proto.InternalMessageInfo

func (m *UserAnimeList_UserAnime) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetIsRewatching() string {
	if m != nil {
		return m.IsRewatching
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetNumWatchedEpisodes() int32 {
	if m != nil {
		return m.NumWatchedEpisodes
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetAnimeTitle() string {
	if m != nil {
		return m.AnimeTitle
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeNumEpisodes() int32 {
	if m != nil {
		return m.AnimeNumEpisodes
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetAnimeAiringStatus() int32 {
	if m != nil {
		return m.AnimeAiringStatus
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetAnimeId() int32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetAnimeStudios() string {
	if m != nil {
		return m.AnimeStudios
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeLicensors() string {
	if m != nil {
		return m.AnimeLicensors
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeSeason() *UserAnimeList_UserAnime_AnimeSeason {
	if m != nil {
		return m.AnimeSeason
	}
	return nil
}

func (m *UserAnimeList_UserAnime) GetHasEpisodeVideo() bool {
	if m != nil {
		return m.HasEpisodeVideo
	}
	return false
}

func (m *UserAnimeList_UserAnime) GetHasPromotionVideo() bool {
	if m != nil {
		return m.HasPromotionVideo
	}
	return false
}

func (m *UserAnimeList_UserAnime) GetHasVideo() bool {
	if m != nil {
		return m.HasVideo
	}
	return false
}

func (m *UserAnimeList_UserAnime) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeUrl() string {
	if m != nil {
		return m.AnimeUrl
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeImagePath() string {
	if m != nil {
		return m.AnimeImagePath
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetIsAddedToList() bool {
	if m != nil {
		return m.IsAddedToList
	}
	return false
}

func (m *UserAnimeList_UserAnime) GetAnimeMediaTypeString() string {
	if m != nil {
		return m.AnimeMediaTypeString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeMpaaRatingString() string {
	if m != nil {
		return m.AnimeMpaaRatingString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetStartDateString() string {
	if m != nil {
		return m.StartDateString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetFinishDateString() string {
	if m != nil {
		return m.FinishDateString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeStartDateString() string {
	if m != nil {
		return m.AnimeStartDateString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetAnimeEndDateString() string {
	if m != nil {
		return m.AnimeEndDateString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetDaysString() int32 {
	if m != nil {
		return m.DaysString
	}
	return 0
}

func (m *UserAnimeList_UserAnime) GetStorageString() string {
	if m != nil {
		return m.StorageString
	}
	return ""
}

func (m *UserAnimeList_UserAnime) GetPriorityString() string {
	if m != nil {
		return m.PriorityString
	}
	return ""
}

type UserAnimeList_UserAnime_AnimeSeason struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Season               string   `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAnimeList_UserAnime_AnimeSeason) Reset()         { *m = UserAnimeList_UserAnime_AnimeSeason{} }
func (m *UserAnimeList_UserAnime_AnimeSeason) String() string { return proto.CompactTextString(m) }
func (*UserAnimeList_UserAnime_AnimeSeason) ProtoMessage()    {}
func (*UserAnimeList_UserAnime_AnimeSeason) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1, 0, 0}
}

func (m *UserAnimeList_UserAnime_AnimeSeason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason.Unmarshal(m, b)
}
func (m *UserAnimeList_UserAnime_AnimeSeason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason.Marshal(b, m, deterministic)
}
func (m *UserAnimeList_UserAnime_AnimeSeason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason.Merge(m, src)
}
func (m *UserAnimeList_UserAnime_AnimeSeason) XXX_Size() int {
	return xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason.Size(m)
}
func (m *UserAnimeList_UserAnime_AnimeSeason) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason.DiscardUnknown(m)
}

var xxx_messageInfo_UserAnimeList_UserAnime_AnimeSeason proto.InternalMessageInfo

func (m *UserAnimeList_UserAnime_AnimeSeason) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *UserAnimeList_UserAnime_AnimeSeason) GetSeason() string {
	if m != nil {
		return m.Season
	}
	return ""
}

type SearchQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchQuery) Reset()         { *m = SearchQuery{} }
func (m *SearchQuery) String() string { return proto.CompactTextString(m) }
func (*SearchQuery) ProtoMessage()    {}
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{2}
}

func (m *SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchQuery.Merge(m, src)
}
func (m *SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchQuery.Size(m)
}
func (m *SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type AnimeSearchResults struct {
	Results              []*AnimeSearchResults_AnimeSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *AnimeSearchResults) Reset()         { *m = AnimeSearchResults{} }
func (m *AnimeSearchResults) String() string { return proto.CompactTextString(m) }
func (*AnimeSearchResults) ProtoMessage()    {}
func (*AnimeSearchResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{3}
}

func (m *AnimeSearchResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeSearchResults.Unmarshal(m, b)
}
func (m *AnimeSearchResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeSearchResults.Marshal(b, m, deterministic)
}
func (m *AnimeSearchResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeSearchResults.Merge(m, src)
}
func (m *AnimeSearchResults) XXX_Size() int {
	return xxx_messageInfo_AnimeSearchResults.Size(m)
}
func (m *AnimeSearchResults) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeSearchResults.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeSearchResults proto.InternalMessageInfo

func (m *AnimeSearchResults) GetResults() []*AnimeSearchResults_AnimeSearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type AnimeSearchResults_AnimeSearchResult struct {
	ImgSrc               string   `protobuf:"bytes,1,opt,name=img_src,json=imgSrc,proto3" json:"img_src,omitempty"`
	ImgBlob              []byte   `protobuf:"bytes,2,opt,name=img_blob,json=imgBlob,proto3" json:"img_blob,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Synopsis             string   `protobuf:"bytes,5,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	NumEpisodes          string   `protobuf:"bytes,7,opt,name=num_episodes,json=numEpisodes,proto3" json:"num_episodes,omitempty"`
	Score                string   `protobuf:"bytes,8,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeSearchResults_AnimeSearchResult) Reset()         { *m = AnimeSearchResults_AnimeSearchResult{} }
func (m *AnimeSearchResults_AnimeSearchResult) String() string { return proto.CompactTextString(m) }
func (*AnimeSearchResults_AnimeSearchResult) ProtoMessage()    {}
func (*AnimeSearchResults_AnimeSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{3, 0}
}

func (m *AnimeSearchResults_AnimeSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeSearchResults_AnimeSearchResult.Unmarshal(m, b)
}
func (m *AnimeSearchResults_AnimeSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeSearchResults_AnimeSearchResult.Marshal(b, m, deterministic)
}
func (m *AnimeSearchResults_AnimeSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeSearchResults_AnimeSearchResult.Merge(m, src)
}
func (m *AnimeSearchResults_AnimeSearchResult) XXX_Size() int {
	return xxx_messageInfo_AnimeSearchResults_AnimeSearchResult.Size(m)
}
func (m *AnimeSearchResults_AnimeSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeSearchResults_AnimeSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeSearchResults_AnimeSearchResult proto.InternalMessageInfo

func (m *AnimeSearchResults_AnimeSearchResult) GetImgSrc() string {
	if m != nil {
		return m.ImgSrc
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetImgBlob() []byte {
	if m != nil {
		return m.ImgBlob
	}
	return nil
}

func (m *AnimeSearchResults_AnimeSearchResult) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetSynopsis() string {
	if m != nil {
		return m.Synopsis
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetNumEpisodes() string {
	if m != nil {
		return m.NumEpisodes
	}
	return ""
}

func (m *AnimeSearchResults_AnimeSearchResult) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

type AnimeLink struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeLink) Reset()         { *m = AnimeLink{} }
func (m *AnimeLink) String() string { return proto.CompactTextString(m) }
func (*AnimeLink) ProtoMessage()    {}
func (*AnimeLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{4}
}

func (m *AnimeLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeLink.Unmarshal(m, b)
}
func (m *AnimeLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeLink.Marshal(b, m, deterministic)
}
func (m *AnimeLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeLink.Merge(m, src)
}
func (m *AnimeLink) XXX_Size() int {
	return xxx_messageInfo_AnimeLink.Size(m)
}
func (m *AnimeLink) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeLink.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeLink proto.InternalMessageInfo

func (m *AnimeLink) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type AnimeID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeID) Reset()         { *m = AnimeID{} }
func (m *AnimeID) String() string { return proto.CompactTextString(m) }
func (*AnimeID) ProtoMessage()    {}
func (*AnimeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{5}
}

func (m *AnimeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeID.Unmarshal(m, b)
}
func (m *AnimeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeID.Marshal(b, m, deterministic)
}
func (m *AnimeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeID.Merge(m, src)
}
func (m *AnimeID) XXX_Size() int {
	return xxx_messageInfo_AnimeID.Size(m)
}
func (m *AnimeID) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeID.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeID proto.InternalMessageInfo

func (m *AnimeID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Anime struct {
	Id                   int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string                  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title                string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ImgSrc               string                  `protobuf:"bytes,4,opt,name=img_src,json=imgSrc,proto3" json:"img_src,omitempty"`
	ImgBlob              []byte                  `protobuf:"bytes,5,opt,name=img_blob,json=imgBlob,proto3" json:"img_blob,omitempty"`
	Description          string                  `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	AltTitles            *Anime_AltTitles        `protobuf:"bytes,7,opt,name=alt_titles,json=altTitles,proto3" json:"alt_titles,omitempty"`
	Info                 *Anime_AnimeInformation `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	Stats                *Anime_AnimeStatistics  `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{6}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Anime) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetImgSrc() string {
	if m != nil {
		return m.ImgSrc
	}
	return ""
}

func (m *Anime) GetImgBlob() []byte {
	if m != nil {
		return m.ImgBlob
	}
	return nil
}

func (m *Anime) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Anime) GetAltTitles() *Anime_AltTitles {
	if m != nil {
		return m.AltTitles
	}
	return nil
}

func (m *Anime) GetInfo() *Anime_AnimeInformation {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Anime) GetStats() *Anime_AnimeStatistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Anime_AltTitles struct {
	Synonyms             string   `protobuf:"bytes,1,opt,name=synonyms,proto3" json:"synonyms,omitempty"`
	English              string   `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`
	Japanese             string   `protobuf:"bytes,3,opt,name=japanese,proto3" json:"japanese,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime_AltTitles) Reset()         { *m = Anime_AltTitles{} }
func (m *Anime_AltTitles) String() string { return proto.CompactTextString(m) }
func (*Anime_AltTitles) ProtoMessage()    {}
func (*Anime_AltTitles) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{6, 0}
}

func (m *Anime_AltTitles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime_AltTitles.Unmarshal(m, b)
}
func (m *Anime_AltTitles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime_AltTitles.Marshal(b, m, deterministic)
}
func (m *Anime_AltTitles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime_AltTitles.Merge(m, src)
}
func (m *Anime_AltTitles) XXX_Size() int {
	return xxx_messageInfo_Anime_AltTitles.Size(m)
}
func (m *Anime_AltTitles) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime_AltTitles.DiscardUnknown(m)
}

var xxx_messageInfo_Anime_AltTitles proto.InternalMessageInfo

func (m *Anime_AltTitles) GetSynonyms() string {
	if m != nil {
		return m.Synonyms
	}
	return ""
}

func (m *Anime_AltTitles) GetEnglish() string {
	if m != nil {
		return m.English
	}
	return ""
}

func (m *Anime_AltTitles) GetJapanese() string {
	if m != nil {
		return m.Japanese
	}
	return ""
}

type Anime_AnimeInformation struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Episodes             string   `protobuf:"bytes,2,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Aired                string   `protobuf:"bytes,4,opt,name=aired,proto3" json:"aired,omitempty"`
	Premiered            string   `protobuf:"bytes,5,opt,name=premiered,proto3" json:"premiered,omitempty"`
	Broadcast            string   `protobuf:"bytes,6,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Producers            string   `protobuf:"bytes,7,opt,name=producers,proto3" json:"producers,omitempty"`
	Licensors            string   `protobuf:"bytes,8,opt,name=licensors,proto3" json:"licensors,omitempty"`
	Studios              string   `protobuf:"bytes,9,opt,name=studios,proto3" json:"studios,omitempty"`
	Source               string   `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Genres               string   `protobuf:"bytes,11,opt,name=genres,proto3" json:"genres,omitempty"`
	Duration             string   `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	Rating               string   `protobuf:"bytes,13,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime_AnimeInformation) Reset()         { *m = Anime_AnimeInformation{} }
func (m *Anime_AnimeInformation) String() string { return proto.CompactTextString(m) }
func (*Anime_AnimeInformation) ProtoMessage()    {}
func (*Anime_AnimeInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{6, 1}
}

func (m *Anime_AnimeInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime_AnimeInformation.Unmarshal(m, b)
}
func (m *Anime_AnimeInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime_AnimeInformation.Marshal(b, m, deterministic)
}
func (m *Anime_AnimeInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime_AnimeInformation.Merge(m, src)
}
func (m *Anime_AnimeInformation) XXX_Size() int {
	return xxx_messageInfo_Anime_AnimeInformation.Size(m)
}
func (m *Anime_AnimeInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime_AnimeInformation.DiscardUnknown(m)
}

var xxx_messageInfo_Anime_AnimeInformation proto.InternalMessageInfo

func (m *Anime_AnimeInformation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Anime_AnimeInformation) GetEpisodes() string {
	if m != nil {
		return m.Episodes
	}
	return ""
}

func (m *Anime_AnimeInformation) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Anime_AnimeInformation) GetAired() string {
	if m != nil {
		return m.Aired
	}
	return ""
}

func (m *Anime_AnimeInformation) GetPremiered() string {
	if m != nil {
		return m.Premiered
	}
	return ""
}

func (m *Anime_AnimeInformation) GetBroadcast() string {
	if m != nil {
		return m.Broadcast
	}
	return ""
}

func (m *Anime_AnimeInformation) GetProducers() string {
	if m != nil {
		return m.Producers
	}
	return ""
}

func (m *Anime_AnimeInformation) GetLicensors() string {
	if m != nil {
		return m.Licensors
	}
	return ""
}

func (m *Anime_AnimeInformation) GetStudios() string {
	if m != nil {
		return m.Studios
	}
	return ""
}

func (m *Anime_AnimeInformation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Anime_AnimeInformation) GetGenres() string {
	if m != nil {
		return m.Genres
	}
	return ""
}

func (m *Anime_AnimeInformation) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Anime_AnimeInformation) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

type Anime_AnimeStatistics struct {
	Score                string   `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	Ranked               string   `protobuf:"bytes,2,opt,name=ranked,proto3" json:"ranked,omitempty"`
	Popularity           string   `protobuf:"bytes,3,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Members              string   `protobuf:"bytes,4,opt,name=members,proto3" json:"members,omitempty"`
	Favorites            string   `protobuf:"bytes,5,opt,name=favorites,proto3" json:"favorites,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime_AnimeStatistics) Reset()         { *m = Anime_AnimeStatistics{} }
func (m *Anime_AnimeStatistics) String() string { return proto.CompactTextString(m) }
func (*Anime_AnimeStatistics) ProtoMessage()    {}
func (*Anime_AnimeStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{6, 2}
}

func (m *Anime_AnimeStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime_AnimeStatistics.Unmarshal(m, b)
}
func (m *Anime_AnimeStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime_AnimeStatistics.Marshal(b, m, deterministic)
}
func (m *Anime_AnimeStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime_AnimeStatistics.Merge(m, src)
}
func (m *Anime_AnimeStatistics) XXX_Size() int {
	return xxx_messageInfo_Anime_AnimeStatistics.Size(m)
}
func (m *Anime_AnimeStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime_AnimeStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_Anime_AnimeStatistics proto.InternalMessageInfo

func (m *Anime_AnimeStatistics) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *Anime_AnimeStatistics) GetRanked() string {
	if m != nil {
		return m.Ranked
	}
	return ""
}

func (m *Anime_AnimeStatistics) GetPopularity() string {
	if m != nil {
		return m.Popularity
	}
	return ""
}

func (m *Anime_AnimeStatistics) GetMembers() string {
	if m != nil {
		return m.Members
	}
	return ""
}

func (m *Anime_AnimeStatistics) GetFavorites() string {
	if m != nil {
		return m.Favorites
	}
	return ""
}

func init() {
	proto.RegisterType((*Username)(nil), "message.Username")
	proto.RegisterType((*UserAnimeList)(nil), "message.UserAnimeList")
	proto.RegisterType((*UserAnimeList_UserAnime)(nil), "message.UserAnimeList.UserAnime")
	proto.RegisterType((*UserAnimeList_UserAnime_AnimeSeason)(nil), "message.UserAnimeList.UserAnime.AnimeSeason")
	proto.RegisterType((*SearchQuery)(nil), "message.SearchQuery")
	proto.RegisterType((*AnimeSearchResults)(nil), "message.AnimeSearchResults")
	proto.RegisterType((*AnimeSearchResults_AnimeSearchResult)(nil), "message.AnimeSearchResults.AnimeSearchResult")
	proto.RegisterType((*AnimeLink)(nil), "message.AnimeLink")
	proto.RegisterType((*AnimeID)(nil), "message.AnimeID")
	proto.RegisterType((*Anime)(nil), "message.Anime")
	proto.RegisterType((*Anime_AltTitles)(nil), "message.Anime.AltTitles")
	proto.RegisterType((*Anime_AnimeInformation)(nil), "message.Anime.AnimeInformation")
	proto.RegisterType((*Anime_AnimeStatistics)(nil), "message.Anime.AnimeStatistics")
}

func init() { proto.RegisterFile("myanimelist.proto", fileDescriptor_7365bf8e2ee52b0c) }

var fileDescriptor_7365bf8e2ee52b0c = []byte{
	// 1259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdd, 0x8e, 0xdc, 0x34,
	0x14, 0xd6, 0xec, 0xdf, 0x4c, 0xce, 0xec, 0xcf, 0xac, 0xbb, 0x6d, 0xd3, 0x69, 0xd5, 0x5d, 0xa6,
	0x82, 0xae, 0xaa, 0x32, 0x03, 0x5b, 0x50, 0xc5, 0x15, 0xda, 0xaa, 0x15, 0x5a, 0xf1, 0x57, 0x32,
	0x2d, 0x48, 0x48, 0x28, 0xf2, 0x24, 0xde, 0x19, 0xd3, 0x24, 0x0e, 0xb6, 0xb3, 0xd5, 0x3c, 0x09,
	0x17, 0xbc, 0x05, 0x97, 0xdc, 0xf2, 0x16, 0x3c, 0x00, 0xcf, 0x81, 0xce, 0xb1, 0x93, 0xc9, 0xee,
	0x52, 0xb8, 0x89, 0x7c, 0xce, 0xf7, 0x9d, 0x63, 0xfb, 0xb3, 0x7d, 0x4e, 0x60, 0x3f, 0x5f, 0xf2,
	0x42, 0xe6, 0x22, 0x93, 0xc6, 0x8e, 0x4b, 0xad, 0xac, 0x62, 0xdd, 0x5c, 0x18, 0xc3, 0xe7, 0x62,
	0xf4, 0x01, 0xf4, 0x5e, 0x1b, 0xa1, 0x0b, 0x9e, 0x0b, 0x36, 0x84, 0x5e, 0xe5, 0xc7, 0x61, 0xe7,
	0xa8, 0x73, 0x1c, 0x44, 0x8d, 0x3d, 0xfa, 0x1d, 0x60, 0x07, 0x89, 0xa7, 0x98, 0xe8, 0x2b, 0x69,
	0xec, 0x7f, 0xb1, 0xd9, 0xe7, 0x00, 0x38, 0x8e, 0x69, 0xda, 0x70, 0xed, 0x68, 0xfd, 0xb8, 0x7f,
	0x72, 0x34, 0xf6, 0x73, 0x8e, 0x2f, 0xe5, 0x59, 0x59, 0x51, 0x50, 0xd5, 0xc3, 0xe1, 0x9f, 0x01,
	0x04, 0x0d, 0xc0, 0x6e, 0xc1, 0x96, 0xb1, 0xdc, 0x56, 0x86, 0x26, 0xda, 0x8c, 0xbc, 0xc5, 0x0e,
	0x60, 0xd3, 0x24, 0x4a, 0xe3, 0x0c, 0xe8, 0x76, 0x06, 0x63, 0xb0, 0x61, 0xf9, 0xdc, 0x84, 0xeb,
	0xb4, 0x28, 0x1a, 0xb3, 0x07, 0xb0, 0x23, 0x4d, 0xac, 0xc5, 0x5b, 0x6e, 0x93, 0x85, 0x2c, 0xe6,
	0xe1, 0x06, 0x81, 0xdb, 0xd2, 0x44, 0x8d, 0x8f, 0x7d, 0x04, 0x07, 0x45, 0x95, 0xc7, 0x64, 0x8b,
	0x34, 0x16, 0xa5, 0x34, 0x2a, 0x15, 0x26, 0xdc, 0xa4, 0xec, 0xac, 0xa8, 0xf2, 0x1f, 0x1c, 0xf4,
	0xc2, 0x23, 0xec, 0x10, 0xfa, 0xb4, 0xc5, 0xd8, 0x4a, 0x9b, 0x89, 0x70, 0x8b, 0x92, 0x02, 0xb9,
	0x5e, 0xa1, 0x87, 0x3d, 0x06, 0xe6, 0x08, 0x98, 0xb8, 0x49, 0xd8, 0xa5, 0x84, 0x03, 0x42, 0xbe,
	0xa9, 0xf2, 0x26, 0xdd, 0x18, 0x6e, 0x38, 0x36, 0x97, 0x5a, 0x16, 0xf3, 0xd8, 0x6f, 0xba, 0x47,
	0xf4, 0x7d, 0x82, 0x4e, 0x09, 0x99, 0xba, 0xfd, 0xdf, 0x81, 0x9e, 0xe3, 0xcb, 0x34, 0x0c, 0x88,
	0xd4, 0x25, 0xfb, 0x2c, 0xc5, 0x0d, 0x3b, 0xc8, 0xd8, 0x2a, 0x95, 0xca, 0x84, 0xe0, 0x36, 0x4c,
	0xce, 0xa9, 0xf3, 0xb1, 0x87, 0xb0, 0xe7, 0x48, 0x99, 0x4c, 0x44, 0x61, 0x94, 0x36, 0x61, 0x9f,
	0x68, 0xbb, 0xdc, 0x1d, 0x8f, 0xf7, 0xb2, 0x6f, 0x61, 0xdb, 0x67, 0x13, 0xdc, 0xa8, 0x22, 0xdc,
	0x3e, 0xea, 0x1c, 0xf7, 0x4f, 0x1e, 0xff, 0xdf, 0x89, 0x8e, 0xe9, 0x3b, 0xa5, 0x98, 0xc8, 0x29,
	0xe5, 0x0c, 0xf6, 0x08, 0xf6, 0x17, 0xdc, 0xd4, 0x8a, 0xc4, 0x17, 0x32, 0x15, 0x2a, 0xdc, 0x39,
	0xea, 0x1c, 0xf7, 0xa2, 0xbd, 0x05, 0x37, 0x5e, 0x91, 0xef, 0xd1, 0x8d, 0xaa, 0x20, 0xb7, 0xd4,
	0x2a, 0x57, 0x56, 0xaa, 0xc2, 0xb3, 0x77, 0x89, 0x8d, 0x69, 0x5e, 0xd6, 0x88, 0xe3, 0xdf, 0x85,
	0x00, 0xf9, 0x8e, 0xb5, 0x47, 0xac, 0xde, 0x82, 0x9b, 0x06, 0x24, 0x20, 0xae, 0x74, 0x16, 0x0e,
	0xdc, 0xb5, 0x25, 0xc7, 0x6b, 0x9d, 0x21, 0xe8, 0xb6, 0x89, 0xe0, 0xbe, 0x03, 0xc9, 0x81, 0xe0,
	0x31, 0x0c, 0xbc, 0xd8, 0x39, 0x9f, 0x8b, 0xb8, 0xe4, 0x76, 0x11, 0xb2, 0x96, 0x5a, 0x67, 0xe8,
	0x7e, 0xc9, 0xed, 0x82, 0x3d, 0x84, 0x81, 0x34, 0x31, 0x4f, 0x53, 0x91, 0xc6, 0x56, 0xc5, 0xf8,
	0xec, 0xc2, 0x1b, 0xb4, 0x8e, 0x1d, 0x69, 0x4e, 0xd1, 0xfd, 0x4a, 0xd1, 0x13, 0xfa, 0x14, 0x6e,
	0xbb, 0x94, 0xb9, 0x48, 0x25, 0x8f, 0xed, 0xb2, 0xc4, 0xf3, 0xc2, 0x03, 0x0e, 0x0f, 0x28, 0xf3,
	0x01, 0xc1, 0x5f, 0x23, 0xfa, 0x6a, 0x59, 0x8a, 0x29, 0x61, 0xec, 0x29, 0x84, 0x3e, 0xac, 0xe4,
	0x3c, 0xd6, 0xdc, 0xba, 0xbb, 0x42, 0x71, 0x37, 0x29, 0xee, 0xa6, 0x8b, 0x2b, 0x39, 0x8f, 0x08,
	0xf5, 0x81, 0x8f, 0x60, 0xdf, 0x58, 0xae, 0x6d, 0x9c, 0x72, 0xdb, 0xcc, 0x74, 0x8b, 0x22, 0xf6,
	0x08, 0x78, 0xce, 0x6d, 0x3d, 0xc9, 0x63, 0x60, 0xe7, 0xb2, 0x90, 0x66, 0x71, 0x89, 0x7c, 0x9b,
	0xc8, 0x03, 0x87, 0xb4, 0xd8, 0xcd, 0x4e, 0xae, 0xe7, 0x0f, 0x5b, 0x3b, 0x99, 0x5e, 0x99, 0xe4,
	0x63, 0x70, 0x2b, 0x8d, 0x45, 0x91, 0x5e, 0x0a, 0xba, 0x43, 0x41, 0xee, 0xed, 0xbc, 0x28, 0xd2,
	0x56, 0xc8, 0x21, 0xf4, 0x53, 0xbe, 0x34, 0x35, 0x71, 0x48, 0xd7, 0x1e, 0xd0, 0xe5, 0x09, 0xef,
	0xc3, 0xae, 0xb1, 0x4a, 0xe3, 0x19, 0x79, 0xce, 0x5d, 0x4a, 0xb6, 0xe3, 0xbd, 0x9e, 0xf6, 0x10,
	0xf6, 0x4a, 0x2d, 0x95, 0x96, 0x76, 0x59, 0xf3, 0xee, 0xb9, 0xd3, 0xac, 0xdd, 0x8e, 0x38, 0xfc,
	0x0c, 0xfa, 0xad, 0x6b, 0x8c, 0xd5, 0x65, 0x29, 0xb8, 0xf6, 0x95, 0x88, 0xc6, 0x54, 0x9f, 0xdc,
	0xc3, 0x58, 0xa3, 0x14, 0xde, 0x1a, 0x3d, 0x80, 0xfe, 0x54, 0x70, 0x9d, 0x2c, 0xbe, 0xab, 0x84,
	0x5e, 0x62, 0xb9, 0xfa, 0x05, 0x07, 0xbe, 0x5c, 0x3a, 0x63, 0xf4, 0xc7, 0x1a, 0xb0, 0x7a, 0x02,
	0x9d, 0x2c, 0x22, 0x61, 0xaa, 0xcc, 0x1a, 0xf6, 0x05, 0x74, 0xb5, 0x1b, 0x86, 0x1d, 0xaa, 0x9f,
	0x1f, 0x36, 0xaf, 0xed, 0x3a, 0xfb, 0xba, 0x2b, 0xaa, 0xa3, 0x87, 0x7f, 0x75, 0x60, 0xff, 0x1a,
	0xcc, 0x6e, 0x43, 0x57, 0xe6, 0xf3, 0xd8, 0xe8, 0xc4, 0xaf, 0x66, 0x4b, 0xe6, 0xf3, 0xa9, 0x4e,
	0xb0, 0xa6, 0x20, 0x30, 0xcb, 0xd4, 0x8c, 0x76, 0xb3, 0x1d, 0x21, 0xf1, 0x59, 0xa6, 0x66, 0xb8,
	0x7e, 0x57, 0xe7, 0x5c, 0x65, 0x75, 0x06, 0x0a, 0x92, 0xc9, 0xe2, 0x8d, 0xaf, 0xa8, 0x34, 0xc6,
	0xde, 0x60, 0x96, 0x85, 0x2a, 0x8d, 0x74, 0xd5, 0x33, 0x88, 0x1a, 0x9b, 0xca, 0xf3, 0xb2, 0xac,
	0x8b, 0x25, 0x8d, 0xd9, 0x7b, 0xb0, 0x7d, 0xad, 0x40, 0x06, 0x51, 0xbf, 0x68, 0xd5, 0xc6, 0xa6,
	0xd6, 0xf7, 0xdc, 0xe4, 0x64, 0x8c, 0x0e, 0x21, 0xf0, 0x75, 0xa7, 0x78, 0xd3, 0xac, 0xa4, 0xb3,
	0x5a, 0xc9, 0xe8, 0x0e, 0x74, 0x89, 0x70, 0xf6, 0x9c, 0xed, 0xc2, 0x9a, 0x4c, 0xfd, 0xb9, 0xad,
	0xc9, 0x74, 0xf4, 0x5b, 0x17, 0x36, 0x5d, 0x7f, 0xb9, 0x82, 0xb0, 0x01, 0xac, 0x63, 0x05, 0x70,
	0x87, 0x89, 0xc3, 0x77, 0x6c, 0xbd, 0x25, 0xe2, 0xc6, 0x3b, 0x45, 0xdc, 0xbc, 0x2c, 0xe2, 0x11,
	0xf4, 0x53, 0x61, 0x12, 0x2d, 0x4b, 0xac, 0x58, 0x5e, 0x85, 0xb6, 0x8b, 0x3d, 0x05, 0xe0, 0x99,
	0x75, 0x2d, 0xc5, 0x49, 0xd1, 0x3f, 0x09, 0x2f, 0x1f, 0xfe, 0xf8, 0x34, 0xb3, 0xd4, 0x60, 0x4c,
	0x14, 0xf0, 0x7a, 0xc8, 0x9e, 0xc0, 0x86, 0x2c, 0xce, 0x15, 0x29, 0xd4, 0x3f, 0x39, 0xbc, 0x1a,
	0x42, 0x32, 0x14, 0xe7, 0x4a, 0xe7, 0x1c, 0xe7, 0x89, 0x88, 0xcc, 0x3e, 0x81, 0x4d, 0x6c, 0x33,
	0x86, 0x1a, 0x48, 0xff, 0xe4, 0xfe, 0xbf, 0x45, 0x61, 0xbb, 0x91, 0xc6, 0xca, 0xc4, 0x44, 0x8e,
	0x3c, 0xfc, 0x09, 0x82, 0x66, 0x09, 0xf5, 0x69, 0x17, 0xcb, 0xdc, 0xd4, 0x7f, 0x02, 0xb5, 0xcd,
	0x42, 0xe8, 0x8a, 0x62, 0x9e, 0x49, 0xb3, 0xf0, 0x72, 0xd6, 0x26, 0x46, 0xfd, 0xcc, 0x4b, 0x5e,
	0x08, 0x53, 0xab, 0xda, 0xd8, 0xc3, 0xbf, 0xd7, 0x60, 0x70, 0x75, 0xbd, 0xcd, 0xc5, 0xe9, 0xb4,
	0x2e, 0xce, 0x10, 0x7a, 0xcd, 0xa5, 0x71, 0xf9, 0x1b, 0xbb, 0xf5, 0xd7, 0xb0, 0xee, 0x5f, 0x65,
	0xf3, 0xd7, 0xc0, 0xa5, 0x16, 0xa9, 0x3f, 0x33, 0x67, 0xb0, 0x7b, 0x10, 0x94, 0x5a, 0xe4, 0x52,
	0x20, 0xe2, 0xee, 0xec, 0xca, 0x81, 0xe8, 0x4c, 0x2b, 0x9e, 0x26, 0xdc, 0x58, 0x7f, 0x66, 0x2b,
	0x87, 0x8b, 0x55, 0x69, 0x95, 0x08, 0x5d, 0xdf, 0xdd, 0x95, 0x03, 0xd1, 0x55, 0x7f, 0x75, 0xb7,
	0x77, 0xe5, 0x40, 0x81, 0xea, 0x16, 0x1d, 0x38, 0x81, 0xbc, 0x49, 0xeb, 0x57, 0x95, 0x4e, 0x84,
	0xef, 0xdd, 0xde, 0x42, 0xff, 0x5c, 0x14, 0x5a, 0xd4, 0xcd, 0xda, 0x5b, 0xa8, 0x45, 0x5a, 0x69,
	0xd2, 0x8a, 0x1a, 0x74, 0x10, 0x35, 0x36, 0xc6, 0xb8, 0x3e, 0x41, 0x4d, 0x36, 0x88, 0xbc, 0x35,
	0xfc, 0xb5, 0x03, 0x7b, 0x57, 0x8e, 0x78, 0xf5, 0xd2, 0x3a, 0xad, 0x97, 0xe6, 0x32, 0x14, 0x6f,
	0x44, 0x5a, 0xd7, 0x38, 0x67, 0xb1, 0xfb, 0x00, 0xa5, 0x2a, 0xab, 0x8c, 0x63, 0xc9, 0xf4, 0x4a,
	0xb7, 0x3c, 0xb8, 0xbf, 0x5c, 0xe4, 0x33, 0x54, 0xc6, 0xe9, 0x5d, 0x9b, 0xa8, 0xcb, 0x39, 0xbf,
	0xc0, 0x52, 0x2b, 0xea, 0x2a, 0xb1, 0x72, 0x3c, 0xfb, 0xf2, 0xc7, 0xb3, 0xb9, 0xb4, 0x8b, 0x6a,
	0x36, 0x4e, 0x54, 0x3e, 0x99, 0x6b, 0x21, 0x8a, 0x5c, 0x25, 0x0b, 0x39, 0xa9, 0x32, 0x2b, 0x73,
	0x6e, 0xc5, 0xc4, 0x08, 0x7d, 0x21, 0x13, 0x61, 0x26, 0x73, 0x6e, 0xc5, 0x5b, 0xbe, 0x9c, 0xd0,
	0xaf, 0xed, 0xa4, 0xf5, 0xb3, 0x3b, 0xf1, 0x77, 0x79, 0xb6, 0x45, 0xd0, 0x93, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x57, 0xea, 0xfc, 0x0a, 0x0b, 0x00, 0x00,
}
