// Code generated by protoc-gen-go. DO NOT EDIT.
// source: torrent.proto

package torrent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The ping message containing the user's name.
type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message containing the greetings
type PingReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ShutdownRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{2}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

func (m *ShutdownRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ShutdownReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownReply) Reset()         { *m = ShutdownReply{} }
func (m *ShutdownReply) String() string { return proto.CompactTextString(m) }
func (*ShutdownReply) ProtoMessage()    {}
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{3}
}

func (m *ShutdownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownReply.Unmarshal(m, b)
}
func (m *ShutdownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownReply.Marshal(b, m, deterministic)
}
func (m *ShutdownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownReply.Merge(m, src)
}
func (m *ShutdownReply) XXX_Size() int {
	return xxx_messageInfo_ShutdownReply.Size(m)
}
func (m *ShutdownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownReply proto.InternalMessageInfo

func (m *ShutdownReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddMagnetUriRequest struct {
	Magnet               string   `protobuf:"bytes,1,opt,name=magnet,proto3" json:"magnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMagnetUriRequest) Reset()         { *m = AddMagnetUriRequest{} }
func (m *AddMagnetUriRequest) String() string { return proto.CompactTextString(m) }
func (*AddMagnetUriRequest) ProtoMessage()    {}
func (*AddMagnetUriRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{4}
}

func (m *AddMagnetUriRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMagnetUriRequest.Unmarshal(m, b)
}
func (m *AddMagnetUriRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMagnetUriRequest.Marshal(b, m, deterministic)
}
func (m *AddMagnetUriRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMagnetUriRequest.Merge(m, src)
}
func (m *AddMagnetUriRequest) XXX_Size() int {
	return xxx_messageInfo_AddMagnetUriRequest.Size(m)
}
func (m *AddMagnetUriRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMagnetUriRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMagnetUriRequest proto.InternalMessageInfo

func (m *AddMagnetUriRequest) GetMagnet() string {
	if m != nil {
		return m.Magnet
	}
	return ""
}

type AddMagnetUriReply struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMagnetUriReply) Reset()         { *m = AddMagnetUriReply{} }
func (m *AddMagnetUriReply) String() string { return proto.CompactTextString(m) }
func (*AddMagnetUriReply) ProtoMessage()    {}
func (*AddMagnetUriReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{5}
}

func (m *AddMagnetUriReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMagnetUriReply.Unmarshal(m, b)
}
func (m *AddMagnetUriReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMagnetUriReply.Marshal(b, m, deterministic)
}
func (m *AddMagnetUriReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMagnetUriReply.Merge(m, src)
}
func (m *AddMagnetUriReply) XXX_Size() int {
	return xxx_messageInfo_AddMagnetUriReply.Size(m)
}
func (m *AddMagnetUriReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMagnetUriReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddMagnetUriReply proto.InternalMessageInfo

func (m *AddMagnetUriReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RemoveTorrentRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTorrentRequest) Reset()         { *m = RemoveTorrentRequest{} }
func (m *RemoveTorrentRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTorrentRequest) ProtoMessage()    {}
func (*RemoveTorrentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{6}
}

func (m *RemoveTorrentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTorrentRequest.Unmarshal(m, b)
}
func (m *RemoveTorrentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTorrentRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTorrentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTorrentRequest.Merge(m, src)
}
func (m *RemoveTorrentRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTorrentRequest.Size(m)
}
func (m *RemoveTorrentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTorrentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTorrentRequest proto.InternalMessageInfo

func (m *RemoveTorrentRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RemoveTorrentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTorrentReply) Reset()         { *m = RemoveTorrentReply{} }
func (m *RemoveTorrentReply) String() string { return proto.CompactTextString(m) }
func (*RemoveTorrentReply) ProtoMessage()    {}
func (*RemoveTorrentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{7}
}

func (m *RemoveTorrentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTorrentReply.Unmarshal(m, b)
}
func (m *RemoveTorrentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTorrentReply.Marshal(b, m, deterministic)
}
func (m *RemoveTorrentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTorrentReply.Merge(m, src)
}
func (m *RemoveTorrentReply) XXX_Size() int {
	return xxx_messageInfo_RemoveTorrentReply.Size(m)
}
func (m *RemoveTorrentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTorrentReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTorrentReply proto.InternalMessageInfo

type PauseTorrentRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseTorrentRequest) Reset()         { *m = PauseTorrentRequest{} }
func (m *PauseTorrentRequest) String() string { return proto.CompactTextString(m) }
func (*PauseTorrentRequest) ProtoMessage()    {}
func (*PauseTorrentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{8}
}

func (m *PauseTorrentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseTorrentRequest.Unmarshal(m, b)
}
func (m *PauseTorrentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseTorrentRequest.Marshal(b, m, deterministic)
}
func (m *PauseTorrentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseTorrentRequest.Merge(m, src)
}
func (m *PauseTorrentRequest) XXX_Size() int {
	return xxx_messageInfo_PauseTorrentRequest.Size(m)
}
func (m *PauseTorrentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseTorrentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseTorrentRequest proto.InternalMessageInfo

func (m *PauseTorrentRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type PauseTorrentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseTorrentReply) Reset()         { *m = PauseTorrentReply{} }
func (m *PauseTorrentReply) String() string { return proto.CompactTextString(m) }
func (*PauseTorrentReply) ProtoMessage()    {}
func (*PauseTorrentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{9}
}

func (m *PauseTorrentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseTorrentReply.Unmarshal(m, b)
}
func (m *PauseTorrentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseTorrentReply.Marshal(b, m, deterministic)
}
func (m *PauseTorrentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseTorrentReply.Merge(m, src)
}
func (m *PauseTorrentReply) XXX_Size() int {
	return xxx_messageInfo_PauseTorrentReply.Size(m)
}
func (m *PauseTorrentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseTorrentReply.DiscardUnknown(m)
}

var xxx_messageInfo_PauseTorrentReply proto.InternalMessageInfo

type ResumeTorrentRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeTorrentRequest) Reset()         { *m = ResumeTorrentRequest{} }
func (m *ResumeTorrentRequest) String() string { return proto.CompactTextString(m) }
func (*ResumeTorrentRequest) ProtoMessage()    {}
func (*ResumeTorrentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{10}
}

func (m *ResumeTorrentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeTorrentRequest.Unmarshal(m, b)
}
func (m *ResumeTorrentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeTorrentRequest.Marshal(b, m, deterministic)
}
func (m *ResumeTorrentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeTorrentRequest.Merge(m, src)
}
func (m *ResumeTorrentRequest) XXX_Size() int {
	return xxx_messageInfo_ResumeTorrentRequest.Size(m)
}
func (m *ResumeTorrentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeTorrentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeTorrentRequest proto.InternalMessageInfo

func (m *ResumeTorrentRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ResumeTorrentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeTorrentReply) Reset()         { *m = ResumeTorrentReply{} }
func (m *ResumeTorrentReply) String() string { return proto.CompactTextString(m) }
func (*ResumeTorrentReply) ProtoMessage()    {}
func (*ResumeTorrentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{11}
}

func (m *ResumeTorrentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeTorrentReply.Unmarshal(m, b)
}
func (m *ResumeTorrentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeTorrentReply.Marshal(b, m, deterministic)
}
func (m *ResumeTorrentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeTorrentReply.Merge(m, src)
}
func (m *ResumeTorrentReply) XXX_Size() int {
	return xxx_messageInfo_ResumeTorrentReply.Size(m)
}
func (m *ResumeTorrentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeTorrentReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeTorrentReply proto.InternalMessageInfo

type TorrentStatus struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Progress             float32  `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	DownloadRate         int32    `protobuf:"zigzag32,4,opt,name=download_rate,json=downloadRate,proto3" json:"download_rate,omitempty"`
	UploadRate           int32    `protobuf:"zigzag32,5,opt,name=upload_rate,json=uploadRate,proto3" json:"upload_rate,omitempty"`
	Peers                int32    `protobuf:"zigzag32,6,opt,name=peers,proto3" json:"peers,omitempty"`
	Seeds                int32    `protobuf:"zigzag32,7,opt,name=seeds,proto3" json:"seeds,omitempty"`
	State                string   `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	TotalSize            uint64   `protobuf:"varint,9,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TorrentStatus) Reset()         { *m = TorrentStatus{} }
func (m *TorrentStatus) String() string { return proto.CompactTextString(m) }
func (*TorrentStatus) ProtoMessage()    {}
func (*TorrentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{12}
}

func (m *TorrentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TorrentStatus.Unmarshal(m, b)
}
func (m *TorrentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TorrentStatus.Marshal(b, m, deterministic)
}
func (m *TorrentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TorrentStatus.Merge(m, src)
}
func (m *TorrentStatus) XXX_Size() int {
	return xxx_messageInfo_TorrentStatus.Size(m)
}
func (m *TorrentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TorrentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TorrentStatus proto.InternalMessageInfo

func (m *TorrentStatus) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TorrentStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TorrentStatus) GetProgress() float32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *TorrentStatus) GetDownloadRate() int32 {
	if m != nil {
		return m.DownloadRate
	}
	return 0
}

func (m *TorrentStatus) GetUploadRate() int32 {
	if m != nil {
		return m.UploadRate
	}
	return 0
}

func (m *TorrentStatus) GetPeers() int32 {
	if m != nil {
		return m.Peers
	}
	return 0
}

func (m *TorrentStatus) GetSeeds() int32 {
	if m != nil {
		return m.Seeds
	}
	return 0
}

func (m *TorrentStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *TorrentStatus) GetTotalSize() uint64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

type AllTorrentStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllTorrentStatusRequest) Reset()         { *m = AllTorrentStatusRequest{} }
func (m *AllTorrentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*AllTorrentStatusRequest) ProtoMessage()    {}
func (*AllTorrentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{13}
}

func (m *AllTorrentStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTorrentStatusRequest.Unmarshal(m, b)
}
func (m *AllTorrentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTorrentStatusRequest.Marshal(b, m, deterministic)
}
func (m *AllTorrentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTorrentStatusRequest.Merge(m, src)
}
func (m *AllTorrentStatusRequest) XXX_Size() int {
	return xxx_messageInfo_AllTorrentStatusRequest.Size(m)
}
func (m *AllTorrentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTorrentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllTorrentStatusRequest proto.InternalMessageInfo

type AllTorrentStatusReply struct {
	AllTorrentStatus     []*TorrentStatus `protobuf:"bytes,1,rep,name=all_torrent_status,json=allTorrentStatus,proto3" json:"all_torrent_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AllTorrentStatusReply) Reset()         { *m = AllTorrentStatusReply{} }
func (m *AllTorrentStatusReply) String() string { return proto.CompactTextString(m) }
func (*AllTorrentStatusReply) ProtoMessage()    {}
func (*AllTorrentStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5390c0f93d3a953f, []int{14}
}

func (m *AllTorrentStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTorrentStatusReply.Unmarshal(m, b)
}
func (m *AllTorrentStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTorrentStatusReply.Marshal(b, m, deterministic)
}
func (m *AllTorrentStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTorrentStatusReply.Merge(m, src)
}
func (m *AllTorrentStatusReply) XXX_Size() int {
	return xxx_messageInfo_AllTorrentStatusReply.Size(m)
}
func (m *AllTorrentStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTorrentStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_AllTorrentStatusReply proto.InternalMessageInfo

func (m *AllTorrentStatusReply) GetAllTorrentStatus() []*TorrentStatus {
	if m != nil {
		return m.AllTorrentStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "torrent.PingRequest")
	proto.RegisterType((*PingReply)(nil), "torrent.PingReply")
	proto.RegisterType((*ShutdownRequest)(nil), "torrent.ShutdownRequest")
	proto.RegisterType((*ShutdownReply)(nil), "torrent.ShutdownReply")
	proto.RegisterType((*AddMagnetUriRequest)(nil), "torrent.AddMagnetUriRequest")
	proto.RegisterType((*AddMagnetUriReply)(nil), "torrent.AddMagnetUriReply")
	proto.RegisterType((*RemoveTorrentRequest)(nil), "torrent.RemoveTorrentRequest")
	proto.RegisterType((*RemoveTorrentReply)(nil), "torrent.RemoveTorrentReply")
	proto.RegisterType((*PauseTorrentRequest)(nil), "torrent.PauseTorrentRequest")
	proto.RegisterType((*PauseTorrentReply)(nil), "torrent.PauseTorrentReply")
	proto.RegisterType((*ResumeTorrentRequest)(nil), "torrent.ResumeTorrentRequest")
	proto.RegisterType((*ResumeTorrentReply)(nil), "torrent.ResumeTorrentReply")
	proto.RegisterType((*TorrentStatus)(nil), "torrent.TorrentStatus")
	proto.RegisterType((*AllTorrentStatusRequest)(nil), "torrent.AllTorrentStatusRequest")
	proto.RegisterType((*AllTorrentStatusReply)(nil), "torrent.AllTorrentStatusReply")
}

func init() { proto.RegisterFile("torrent.proto", fileDescriptor_5390c0f93d3a953f) }

var fileDescriptor_5390c0f93d3a953f = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xba, 0xae, 0x1f, 0xb7, 0x8b, 0x58, 0xdd, 0x52, 0x4c, 0xd8, 0x20, 0x0a, 0x42, 0xeb,
	0x86, 0x58, 0xd1, 0x78, 0x43, 0xbc, 0x4c, 0xe2, 0x01, 0x81, 0x90, 0xa6, 0x14, 0x78, 0x43, 0x95,
	0x51, 0xad, 0x34, 0x92, 0x1b, 0x87, 0xd8, 0x01, 0x75, 0x8f, 0xfc, 0x05, 0x9e, 0xf8, 0x5d, 0xfc,
	0x05, 0x7e, 0x05, 0x4f, 0xc8, 0x8e, 0xd3, 0x26, 0x69, 0x56, 0xf6, 0x96, 0x7b, 0xee, 0xb9, 0x47,
	0xc7, 0xf6, 0x3d, 0x01, 0x5b, 0xf2, 0x24, 0xa1, 0x91, 0x3c, 0x8f, 0x13, 0x2e, 0x39, 0x6a, 0x9b,
	0xd2, 0x39, 0x0a, 0x38, 0x0f, 0x18, 0x9d, 0x90, 0x38, 0x9c, 0x90, 0x28, 0xe2, 0x92, 0xc8, 0x90,
	0x47, 0x22, 0xa3, 0x79, 0x27, 0xd0, 0xbb, 0x0a, 0xa3, 0xc0, 0xa7, 0x5f, 0x53, 0x2a, 0x24, 0xc2,
	0xd0, 0x5e, 0x52, 0x21, 0x48, 0x40, 0xb1, 0xe5, 0x5a, 0xe3, 0xae, 0x9f, 0x97, 0xde, 0x13, 0xe8,
	0x66, 0xc4, 0x98, 0xad, 0x76, 0xd0, 0x9e, 0xc2, 0x9d, 0xe9, 0x22, 0x95, 0x73, 0xfe, 0x3d, 0xfa,
	0xbf, 0xe6, 0x29, 0xd8, 0x1b, 0xf2, 0x6e, 0xdd, 0x67, 0x30, 0xb8, 0x9c, 0xcf, 0xdf, 0x93, 0x20,
	0xa2, 0xf2, 0x63, 0x12, 0xe6, 0xda, 0x23, 0x68, 0x2d, 0x35, 0x66, 0xf8, 0xa6, 0xf2, 0x4e, 0xa0,
	0x5f, 0xa6, 0x2b, 0x75, 0x04, 0xcd, 0x05, 0x11, 0x0b, 0x43, 0xd5, 0xdf, 0xde, 0x19, 0x0c, 0x7d,
	0xba, 0xe4, 0xdf, 0xe8, 0x87, 0xec, 0xba, 0x72, 0xe1, 0x3a, 0xee, 0x10, 0x50, 0x85, 0x1b, 0xb3,
	0x95, 0x77, 0x0a, 0x83, 0x2b, 0x92, 0x8a, 0xdb, 0x08, 0x0c, 0xa0, 0x5f, 0xa6, 0xaa, 0x79, 0xed,
	0x40, 0xa4, 0xcb, 0x5b, 0x3b, 0x28, 0x71, 0x95, 0xc2, 0x5f, 0x0b, 0x6c, 0x03, 0x4c, 0x25, 0x91,
	0xa9, 0xa8, 0x9b, 0x55, 0x58, 0x44, 0x96, 0x14, 0x37, 0x32, 0x4c, 0x7d, 0x23, 0x07, 0x3a, 0x71,
	0xc2, 0x83, 0x84, 0x0a, 0x81, 0xf7, 0x5c, 0x6b, 0xdc, 0xf0, 0xd7, 0x35, 0x7a, 0x0c, 0xb6, 0x7a,
	0x18, 0xc6, 0xc9, 0x7c, 0x96, 0x10, 0x49, 0x71, 0xd3, 0xb5, 0xc6, 0x7d, 0xff, 0x20, 0x07, 0x7d,
	0x22, 0x29, 0x7a, 0x04, 0xbd, 0x34, 0xde, 0x50, 0xf6, 0x35, 0x05, 0x32, 0x48, 0x13, 0x86, 0xb0,
	0x1f, 0x53, 0x9a, 0x08, 0xdc, 0xd2, 0xad, 0xac, 0x50, 0xa8, 0xa0, 0x74, 0x2e, 0x70, 0x3b, 0x43,
	0x75, 0xa1, 0x51, 0xa9, 0x64, 0x3a, 0xda, 0x62, 0x56, 0xa0, 0x63, 0x00, 0xc9, 0x25, 0x61, 0x33,
	0x11, 0x5e, 0x53, 0xdc, 0x75, 0xad, 0x71, 0xd3, 0xef, 0x6a, 0x64, 0x1a, 0x5e, 0x53, 0xef, 0x3e,
	0xdc, 0xbb, 0x64, 0xac, 0x74, 0x7c, 0x73, 0x83, 0xde, 0x67, 0xb8, 0xbb, 0xdd, 0x52, 0x8b, 0xf0,
	0x1a, 0x10, 0x61, 0x6c, 0x66, 0x12, 0x32, 0x13, 0xba, 0x85, 0x2d, 0x77, 0x6f, 0xdc, 0xbb, 0x18,
	0x9d, 0xe7, 0x39, 0x2a, 0x0f, 0x1e, 0x92, 0x8a, 0xd4, 0xc5, 0xaf, 0x26, 0xb4, 0x0d, 0x82, 0xde,
	0x42, 0x53, 0xa5, 0x03, 0x0d, 0xd7, 0xd3, 0x85, 0x54, 0x39, 0xa8, 0x82, 0xaa, 0x47, 0xc3, 0x3f,
	0x7e, 0xff, 0xf9, 0xd9, 0x40, 0x9e, 0x3d, 0x31, 0xbd, 0x49, 0x1c, 0x46, 0xc1, 0x4b, 0xeb, 0x0c,
	0xbd, 0x82, 0x4e, 0x9e, 0x0a, 0x84, 0xd7, 0x93, 0x95, 0x54, 0x39, 0xa3, 0x9a, 0x8e, 0x3a, 0xdb,
	0x1b, 0x38, 0x28, 0x6e, 0x3e, 0x3a, 0x5a, 0xf3, 0x6a, 0xf2, 0xe3, 0x38, 0x37, 0x74, 0x95, 0xd2,
	0x3b, 0xb0, 0x4b, 0xeb, 0x8e, 0x8e, 0xd7, 0xe4, 0xba, 0xc8, 0x38, 0x0f, 0x6e, 0x6a, 0x1b, 0x5b,
	0xc5, 0xd5, 0x2f, 0xd8, 0xaa, 0x09, 0x4f, 0xc1, 0xd6, 0x56, 0x5e, 0x32, 0x5b, 0x85, 0x0c, 0x94,
	0x6c, 0x6d, 0xe7, 0xa8, 0x64, 0xab, 0x1a, 0x1d, 0xf4, 0x09, 0x0e, 0xab, 0x2b, 0x82, 0xdc, 0xcd,
	0x9d, 0xd4, 0x2f, 0x96, 0xf3, 0x70, 0x07, 0x23, 0x66, 0xab, 0xe7, 0xd6, 0x97, 0x96, 0xfe, 0xbb,
	0xbe, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x71, 0xcd, 0x9d, 0x95, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TorrentClient is the client API for Torrent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TorrentClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	AddMagnetUri(ctx context.Context, in *AddMagnetUriRequest, opts ...grpc.CallOption) (*AddMagnetUriReply, error)
	RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentReply, error)
	PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*PauseTorrentReply, error)
	ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*ResumeTorrentReply, error)
	AllTorrentStatus(ctx context.Context, in *AllTorrentStatusRequest, opts ...grpc.CallOption) (Torrent_AllTorrentStatusClient, error)
}

type torrentClient struct {
	cc *grpc.ClientConn
}

func NewTorrentClient(cc *grpc.ClientConn) TorrentClient {
	return &torrentClient{cc}
}

func (c *torrentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) AddMagnetUri(ctx context.Context, in *AddMagnetUriRequest, opts ...grpc.CallOption) (*AddMagnetUriReply, error) {
	out := new(AddMagnetUriReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/AddMagnetUri", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) RemoveTorrent(ctx context.Context, in *RemoveTorrentRequest, opts ...grpc.CallOption) (*RemoveTorrentReply, error) {
	out := new(RemoveTorrentReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/RemoveTorrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*PauseTorrentReply, error) {
	out := new(PauseTorrentReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/PauseTorrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*ResumeTorrentReply, error) {
	out := new(ResumeTorrentReply)
	err := c.cc.Invoke(ctx, "/torrent.Torrent/ResumeTorrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentClient) AllTorrentStatus(ctx context.Context, in *AllTorrentStatusRequest, opts ...grpc.CallOption) (Torrent_AllTorrentStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Torrent_serviceDesc.Streams[0], "/torrent.Torrent/AllTorrentStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &torrentAllTorrentStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Torrent_AllTorrentStatusClient interface {
	Recv() (*AllTorrentStatusReply, error)
	grpc.ClientStream
}

type torrentAllTorrentStatusClient struct {
	grpc.ClientStream
}

func (x *torrentAllTorrentStatusClient) Recv() (*AllTorrentStatusReply, error) {
	m := new(AllTorrentStatusReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TorrentServer is the server API for Torrent service.
type TorrentServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	AddMagnetUri(context.Context, *AddMagnetUriRequest) (*AddMagnetUriReply, error)
	RemoveTorrent(context.Context, *RemoveTorrentRequest) (*RemoveTorrentReply, error)
	PauseTorrent(context.Context, *PauseTorrentRequest) (*PauseTorrentReply, error)
	ResumeTorrent(context.Context, *ResumeTorrentRequest) (*ResumeTorrentReply, error)
	AllTorrentStatus(*AllTorrentStatusRequest, Torrent_AllTorrentStatusServer) error
}

// UnimplementedTorrentServer can be embedded to have forward compatible implementations.
type UnimplementedTorrentServer struct {
}

func (*UnimplementedTorrentServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedTorrentServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (*UnimplementedTorrentServer) AddMagnetUri(ctx context.Context, req *AddMagnetUriRequest) (*AddMagnetUriReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMagnetUri not implemented")
}
func (*UnimplementedTorrentServer) RemoveTorrent(ctx context.Context, req *RemoveTorrentRequest) (*RemoveTorrentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTorrent not implemented")
}
func (*UnimplementedTorrentServer) PauseTorrent(ctx context.Context, req *PauseTorrentRequest) (*PauseTorrentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseTorrent not implemented")
}
func (*UnimplementedTorrentServer) ResumeTorrent(ctx context.Context, req *ResumeTorrentRequest) (*ResumeTorrentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeTorrent not implemented")
}
func (*UnimplementedTorrentServer) AllTorrentStatus(req *AllTorrentStatusRequest, srv Torrent_AllTorrentStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method AllTorrentStatus not implemented")
}

func RegisterTorrentServer(s *grpc.Server, srv TorrentServer) {
	s.RegisterService(&_Torrent_serviceDesc, srv)
}

func _Torrent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_AddMagnetUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMagnetUriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).AddMagnetUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/AddMagnetUri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).AddMagnetUri(ctx, req.(*AddMagnetUriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_RemoveTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).RemoveTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/RemoveTorrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).RemoveTorrent(ctx, req.(*RemoveTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_PauseTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).PauseTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/PauseTorrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).PauseTorrent(ctx, req.(*PauseTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_ResumeTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServer).ResumeTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/torrent.Torrent/ResumeTorrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServer).ResumeTorrent(ctx, req.(*ResumeTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrent_AllTorrentStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllTorrentStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TorrentServer).AllTorrentStatus(m, &torrentAllTorrentStatusServer{stream})
}

type Torrent_AllTorrentStatusServer interface {
	Send(*AllTorrentStatusReply) error
	grpc.ServerStream
}

type torrentAllTorrentStatusServer struct {
	grpc.ServerStream
}

func (x *torrentAllTorrentStatusServer) Send(m *AllTorrentStatusReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Torrent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "torrent.Torrent",
	HandlerType: (*TorrentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Torrent_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Torrent_Shutdown_Handler,
		},
		{
			MethodName: "AddMagnetUri",
			Handler:    _Torrent_AddMagnetUri_Handler,
		},
		{
			MethodName: "RemoveTorrent",
			Handler:    _Torrent_RemoveTorrent_Handler,
		},
		{
			MethodName: "PauseTorrent",
			Handler:    _Torrent_PauseTorrent_Handler,
		},
		{
			MethodName: "ResumeTorrent",
			Handler:    _Torrent_ResumeTorrent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllTorrentStatus",
			Handler:       _Torrent_AllTorrentStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "torrent.proto",
}
