// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myanimelist.proto

package myanimelist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	message "github.com/greenmochi/ultimate/services/gateway/proto/myanimelist/message"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7365bf8e2ee52b0c, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "myanimelist.PingRequest")
	proto.RegisterType((*PingReply)(nil), "myanimelist.PingReply")
}

func init() { proto.RegisterFile("myanimelist.proto", fileDescriptor_7365bf8e2ee52b0c) }

var fileDescriptor_7365bf8e2ee52b0c = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0x11, 0xa5, 0xe9, 0xc6, 0x99, 0x45, 0x19, 0x87, 0x0a, 0x12, 0x10, 0x4b, 0x17,
	0x13, 0xd0, 0x5d, 0x77, 0xd5, 0x85, 0x1b, 0x05, 0x29, 0xe8, 0xc2, 0x5d, 0x3a, 0x5c, 0xd2, 0x0b,
	0x93, 0x1f, 0x27, 0x77, 0x94, 0x6c, 0x7d, 0x05, 0xdf, 0xcb, 0x8d, 0xaf, 0xe0, 0x83, 0xc8, 0x4c,
	0xab, 0xc6, 0xbf, 0x65, 0x4e, 0xbe, 0x7c, 0xe7, 0x10, 0x96, 0xea, 0x20, 0x0d, 0x6a, 0xa8, 0xd1,
	0x53, 0xe9, 0x1a, 0x4b, 0x36, 0x1b, 0x46, 0x51, 0x31, 0x56, 0xd6, 0xaa, 0x1a, 0x84, 0x74, 0x28,
	0xa4, 0x31, 0x96, 0x24, 0xa1, 0x35, 0x7e, 0x8d, 0x16, 0xfb, 0x1a, 0xbc, 0x97, 0x0a, 0xc4, 0x2f,
	0x0b, 0x3f, 0x66, 0xc3, 0x6b, 0x34, 0x6a, 0x01, 0xf7, 0x2d, 0x78, 0xca, 0x72, 0xb6, 0xbb, 0x61,
	0xf3, 0xe4, 0x30, 0x99, 0x0c, 0x16, 0x1f, 0x47, 0x7e, 0xc4, 0x06, 0x6b, 0xd0, 0xd5, 0xe1, 0x7f,
	0xec, 0xe4, 0x25, 0x61, 0xc3, 0xab, 0x30, 0xef, 0x5a, 0x2e, 0xd1, 0x53, 0x76, 0xcb, 0xb6, 0xbb,
	0x67, 0x59, 0x5e, 0xc6, 0xdd, 0x51, 0x65, 0x31, 0xfa, 0xe3, 0xc6, 0xd5, 0x81, 0x8f, 0x9f, 0x5e,
	0xdf, 0x9e, 0xb7, 0x46, 0x3c, 0x8d, 0x57, 0x0b, 0x87, 0x46, 0xcd, 0x92, 0x69, 0xa6, 0xd8, 0xde,
	0x05, 0xd0, 0x8d, 0x87, 0xe6, 0xab, 0x2b, 0x2d, 0x37, 0x2b, 0xca, 0x2e, 0x37, 0x52, 0x43, 0x27,
	0x8f, 0xa2, 0x4f, 0x94, 0x4f, 0x7a, 0x39, 0xe7, 0x07, 0xdf, 0xe4, 0x3f, 0x8d, 0xb3, 0x64, 0x7a,
	0x76, 0x7e, 0x37, 0x57, 0x48, 0xab, 0x76, 0x59, 0x56, 0x56, 0x0b, 0xd5, 0x00, 0x18, 0x6d, 0xab,
	0x15, 0x8a, 0xb6, 0x26, 0xd4, 0x92, 0x40, 0x78, 0x68, 0x1e, 0xb0, 0x02, 0x2f, 0x94, 0x24, 0x78,
	0x94, 0x41, 0xf4, 0x3f, 0x1b, 0x8b, 0x97, 0x3b, 0x7d, 0x74, 0xfa, 0x1e, 0x00, 0x00, 0xff, 0xff,
	0x49, 0xfc, 0x89, 0x21, 0xc7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyAnimeListClient is the client API for MyAnimeList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyAnimeListClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetUserAnimeList(ctx context.Context, in *message.Username, opts ...grpc.CallOption) (*message.UserAnimeList, error)
}

type myAnimeListClient struct {
	cc *grpc.ClientConn
}

func NewMyAnimeListClient(cc *grpc.ClientConn) MyAnimeListClient {
	return &myAnimeListClient{cc}
}

func (c *myAnimeListClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myAnimeListClient) GetUserAnimeList(ctx context.Context, in *message.Username, opts ...grpc.CallOption) (*message.UserAnimeList, error) {
	out := new(message.UserAnimeList)
	err := c.cc.Invoke(ctx, "/myanimelist.MyAnimeList/GetUserAnimeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyAnimeListServer is the server API for MyAnimeList service.
type MyAnimeListServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetUserAnimeList(context.Context, *message.Username) (*message.UserAnimeList, error)
}

// UnimplementedMyAnimeListServer can be embedded to have forward compatible implementations.
type UnimplementedMyAnimeListServer struct {
}

func (*UnimplementedMyAnimeListServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMyAnimeListServer) GetUserAnimeList(ctx context.Context, req *message.Username) (*message.UserAnimeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAnimeList not implemented")
}

func RegisterMyAnimeListServer(s *grpc.Server, srv MyAnimeListServer) {
	s.RegisterService(&_MyAnimeList_serviceDesc, srv)
}

func _MyAnimeList_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyAnimeList_GetUserAnimeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAnimeListServer).GetUserAnimeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myanimelist.MyAnimeList/GetUserAnimeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAnimeListServer).GetUserAnimeList(ctx, req.(*message.Username))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyAnimeList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myanimelist.MyAnimeList",
	HandlerType: (*MyAnimeListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MyAnimeList_Ping_Handler,
		},
		{
			MethodName: "GetUserAnimeList",
			Handler:    _MyAnimeList_GetUserAnimeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myanimelist.proto",
}
