# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_engine/proto/youtubedl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_engine/proto/youtubedl.proto',
  package='youtubdl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"hydro_engine/proto/youtubedl.proto\x12\x08youtubdl\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0c\x44ownloadItem\x12\x0b\n\x03url\x18\x01 \x01(\t\"\"\n\x14\x44ownloadItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\nDownloadID\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x16\x44ownloadRemoveResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x13\x41llDownloadsRequest\"5\n\x0c\x41llDownloads\x12%\n\tdownloads\x18\x01 \x03(\x0b\x32\x12.youtubdl.Download\"\xf2\x01\n\x08\x44ownload\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12/\n\x05state\x18\x03 \x01(\x0b\x32 .youtubdl.Download.DownloadState\x1a\x98\x01\n\rDownloadState\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0btmpfilename\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0f\n\x07\x65ta_str\x18\x04 \x01(\t\x12\x13\n\x0bpercent_str\x18\x05 \x01(\t\x12\x11\n\tspeed_str\x18\x06 \x01(\t\x12\x17\n\x0ftotal_bytes_str\x18\x07 \x01(\t2\x9a\x02\n\tYoutubeDL\x12\x32\n\x04Ping\x12\x15.youtubdl.PingRequest\x1a\x13.youtubdl.PingReply\x12\x44\n\nAddToQueue\x12\x16.youtubdl.DownloadItem\x1a\x1e.youtubdl.DownloadItemResponse\x12I\n\x0fRemoveFromQueue\x12\x14.youtubdl.DownloadID\x1a .youtubdl.DownloadRemoveResponse\x12H\n\x0fGetAllDownloads\x12\x1d.youtubdl.AllDownloadsRequest\x1a\x16.youtubdl.AllDownloadsb\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='youtubdl.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='youtubdl.PingRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)


_PINGREPLY = _descriptor.Descriptor(
  name='PingReply',
  full_name='youtubdl.PingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='youtubdl.PingReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=108,
)


_DOWNLOADITEM = _descriptor.Descriptor(
  name='DownloadItem',
  full_name='youtubdl.DownloadItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='youtubdl.DownloadItem.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=137,
)


_DOWNLOADITEMRESPONSE = _descriptor.Descriptor(
  name='DownloadItemResponse',
  full_name='youtubdl.DownloadItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='youtubdl.DownloadItemResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=173,
)


_DOWNLOADID = _descriptor.Descriptor(
  name='DownloadID',
  full_name='youtubdl.DownloadID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='youtubdl.DownloadID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=199,
)


_DOWNLOADREMOVERESPONSE = _descriptor.Descriptor(
  name='DownloadRemoveResponse',
  full_name='youtubdl.DownloadRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='youtubdl.DownloadRemoveResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=242,
)


_ALLDOWNLOADSREQUEST = _descriptor.Descriptor(
  name='AllDownloadsRequest',
  full_name='youtubdl.AllDownloadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=265,
)


_ALLDOWNLOADS = _descriptor.Descriptor(
  name='AllDownloads',
  full_name='youtubdl.AllDownloads',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downloads', full_name='youtubdl.AllDownloads.downloads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=320,
)


_DOWNLOAD_DOWNLOADSTATE = _descriptor.Descriptor(
  name='DownloadState',
  full_name='youtubdl.Download.DownloadState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='youtubdl.Download.DownloadState.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tmpfilename', full_name='youtubdl.Download.DownloadState.tmpfilename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='youtubdl.Download.DownloadState.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eta_str', full_name='youtubdl.Download.DownloadState.eta_str', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_str', full_name='youtubdl.Download.DownloadState.percent_str', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_str', full_name='youtubdl.Download.DownloadState.speed_str', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes_str', full_name='youtubdl.Download.DownloadState.total_bytes_str', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=565,
)

_DOWNLOAD = _descriptor.Descriptor(
  name='Download',
  full_name='youtubdl.Download',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='youtubdl.Download.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='youtubdl.Download.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='youtubdl.Download.state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOWNLOAD_DOWNLOADSTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=565,
)

_ALLDOWNLOADS.fields_by_name['downloads'].message_type = _DOWNLOAD
_DOWNLOAD_DOWNLOADSTATE.containing_type = _DOWNLOAD
_DOWNLOAD.fields_by_name['state'].message_type = _DOWNLOAD_DOWNLOADSTATE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingReply'] = _PINGREPLY
DESCRIPTOR.message_types_by_name['DownloadItem'] = _DOWNLOADITEM
DESCRIPTOR.message_types_by_name['DownloadItemResponse'] = _DOWNLOADITEMRESPONSE
DESCRIPTOR.message_types_by_name['DownloadID'] = _DOWNLOADID
DESCRIPTOR.message_types_by_name['DownloadRemoveResponse'] = _DOWNLOADREMOVERESPONSE
DESCRIPTOR.message_types_by_name['AllDownloadsRequest'] = _ALLDOWNLOADSREQUEST
DESCRIPTOR.message_types_by_name['AllDownloads'] = _ALLDOWNLOADS
DESCRIPTOR.message_types_by_name['Download'] = _DOWNLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), {
  'DESCRIPTOR' : _PINGREPLY,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.PingReply)
  })
_sym_db.RegisterMessage(PingReply)

DownloadItem = _reflection.GeneratedProtocolMessageType('DownloadItem', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADITEM,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.DownloadItem)
  })
_sym_db.RegisterMessage(DownloadItem)

DownloadItemResponse = _reflection.GeneratedProtocolMessageType('DownloadItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADITEMRESPONSE,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.DownloadItemResponse)
  })
_sym_db.RegisterMessage(DownloadItemResponse)

DownloadID = _reflection.GeneratedProtocolMessageType('DownloadID', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADID,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.DownloadID)
  })
_sym_db.RegisterMessage(DownloadID)

DownloadRemoveResponse = _reflection.GeneratedProtocolMessageType('DownloadRemoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADREMOVERESPONSE,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.DownloadRemoveResponse)
  })
_sym_db.RegisterMessage(DownloadRemoveResponse)

AllDownloadsRequest = _reflection.GeneratedProtocolMessageType('AllDownloadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLDOWNLOADSREQUEST,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.AllDownloadsRequest)
  })
_sym_db.RegisterMessage(AllDownloadsRequest)

AllDownloads = _reflection.GeneratedProtocolMessageType('AllDownloads', (_message.Message,), {
  'DESCRIPTOR' : _ALLDOWNLOADS,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.AllDownloads)
  })
_sym_db.RegisterMessage(AllDownloads)

Download = _reflection.GeneratedProtocolMessageType('Download', (_message.Message,), {

  'DownloadState' : _reflection.GeneratedProtocolMessageType('DownloadState', (_message.Message,), {
    'DESCRIPTOR' : _DOWNLOAD_DOWNLOADSTATE,
    '__module__' : 'hydro_engine.proto.youtubedl_pb2'
    # @@protoc_insertion_point(class_scope:youtubdl.Download.DownloadState)
    })
  ,
  'DESCRIPTOR' : _DOWNLOAD,
  '__module__' : 'hydro_engine.proto.youtubedl_pb2'
  # @@protoc_insertion_point(class_scope:youtubdl.Download)
  })
_sym_db.RegisterMessage(Download)
_sym_db.RegisterMessage(Download.DownloadState)



_YOUTUBEDL = _descriptor.ServiceDescriptor(
  name='YoutubeDL',
  full_name='youtubdl.YoutubeDL',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=568,
  serialized_end=850,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='youtubdl.YoutubeDL.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddToQueue',
    full_name='youtubdl.YoutubeDL.AddToQueue',
    index=1,
    containing_service=None,
    input_type=_DOWNLOADITEM,
    output_type=_DOWNLOADITEMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveFromQueue',
    full_name='youtubdl.YoutubeDL.RemoveFromQueue',
    index=2,
    containing_service=None,
    input_type=_DOWNLOADID,
    output_type=_DOWNLOADREMOVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllDownloads',
    full_name='youtubdl.YoutubeDL.GetAllDownloads',
    index=3,
    containing_service=None,
    input_type=_ALLDOWNLOADSREQUEST,
    output_type=_ALLDOWNLOADS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOUTUBEDL)

DESCRIPTOR.services_by_name['YoutubeDL'] = _YOUTUBEDL

# @@protoc_insertion_point(module_scope)
